/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.ucsal.sage.collector.view;

import java.awt.Color;
import java.awt.GridLayout;
import java.sql.Connection;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;

import br.ucsal.sage.collector.controller.CollectorController;
import br.ucsal.sage.request.controller.RequestController;
import br.ucsal.sage.request.model.Request;
import br.ucsal.sage.request.view.RequestDetailsView;
import br.ucsal.sage.user.model.User;
import br.ucsal.sage.user.view.CanvasBackground;
import br.ucsal.sage.user.view.MyProfileView;

/**
 *
 * @author Suporte TI
 */
public class PageCollectorView extends javax.swing.JFrame {

	private static final long serialVersionUID = 1L;
	/**
	 * Creates new form Principal
	 */

	private ArrayList<Request> chamadosAbertos;
	private CollectorController controller;
	private RequestController rcontroller;
	private Request chamado;
	private CanvasBackground tela;
	private static Connection conect;
	private static User usuario;
	private DateTimeFormatter hora = DateTimeFormatter.ofPattern("HH:mm:ss");

	public static void setUsuario(User u) {
		usuario = u;
	}

	public static void setConect(Connection c) {
		conect = c;
	}

	public PageCollectorView() throws SQLException {

		initComponents();
		setExtendedState(MAXIMIZED_BOTH);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 * 
	 * @throws SQLException
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() throws SQLException {

		setLayout(new GridLayout());
		tela = new CanvasBackground("src/Imagens/tela_inicial_coletor.png");
		controller = new CollectorController();
		chamadosAbertos = controller.getAllOpenRequests(conect);
		Object[][] ob = controller.generateObjectArray(chamadosAbertos);

		jButtonMeuPerfil = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTableColetasAbertas = new javax.swing.JTable();
		jLabelTituloPagina = new javax.swing.JLabel();
		jTextFieldBuscar = new javax.swing.JTextField();
		jButtonBuscar = new javax.swing.JButton();
		jScrollPane2 = new javax.swing.JScrollPane();
		jLabelBemVindo = new javax.swing.JTextArea();
		jButtonAtualizar = new javax.swing.JButton();
		jLabelAtualizacaoMensagem = new javax.swing.JLabel();

		jScrollPane1.setBorder(null);

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jScrollPane2.setBackground(new Color(0, 0, 0, 0));
		jScrollPane2.setBorder(null);
		jScrollPane2.getViewport().setBackground(new Color(0, 0, 0, 0));

		
		jLabelBemVindo.setText("Bem vindo, " + usuario.getNome() + "!");
		jLabelBemVindo.setEditable(false);
		jLabelBemVindo.setBackground(new Color(0, 0, 0, 0));
		jLabelBemVindo.setColumns(20);
		jLabelBemVindo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
		jLabelBemVindo.setRows(5);
		jLabelBemVindo.setWrapStyleWord(true);
		jLabelBemVindo.setBorder(null);
		jScrollPane2.setViewportView(jLabelBemVindo);

		jButtonMeuPerfil.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
		jButtonMeuPerfil.setForeground(new java.awt.Color(51, 153, 0));
		jButtonMeuPerfil.setBackground(Color.WHITE);
		jButtonMeuPerfil.setText("Meu perfil");
		jButtonMeuPerfil.setBorder(null);
		jButtonMeuPerfil.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButtonMeuPerfilActionPerformed(evt);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		jTableColetasAbertas.setBackground(new java.awt.Color(102, 204, 0));
		jTableColetasAbertas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
		jTableColetasAbertas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
		jTableColetasAbertas.setForeground(new java.awt.Color(255, 255, 255));
		jTableColetasAbertas.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				try {
					jTableColetasAbertasMouseClicked(evt);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});
		jTableColetasAbertas.setModel(new javax.swing.table.DefaultTableModel(ob,
				new String[] { "Código", "Nome da Escola", "Tipo de Lixo", "Data de Abertura" }) {
			Class[] types = new Class[] { java.lang.String.class, java.lang.String.class, java.lang.String.class,
					java.lang.String.class };
			boolean[] canEdit = new boolean[] { false, false, false, false };

			public Class getColumnClass(int columnIndex) {
				return types[columnIndex];
			}

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jTableColetasAbertas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		jTableColetasAbertas.setGridColor(new java.awt.Color(255, 255, 255));
		jTableColetasAbertas.setSelectionBackground(new java.awt.Color(153, 255, 153));
		jTableColetasAbertas.setSelectionForeground(new java.awt.Color(102, 102, 102));
		jTableColetasAbertas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		jTableColetasAbertas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		jTableColetasAbertas.setShowGrid(true);
		jTableColetasAbertas.setRowHeight(50);
		jTableColetasAbertas.getColumnModel().getColumn(0).setPreferredWidth(100);
		jTableColetasAbertas.getColumnModel().getColumn(1).setPreferredWidth(900);
		jTableColetasAbertas.getColumnModel().getColumn(2).setPreferredWidth(300);
		jTableColetasAbertas.getColumnModel().getColumn(3).setPreferredWidth(100);
		jScrollPane1.setViewportView(jTableColetasAbertas);
		jScrollPane1.getViewport().setBackground(Color.WHITE);

		jLabelTituloPagina.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
		jLabelTituloPagina.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		jLabelTituloPagina.setText("Coletas abertas:");

		jTextFieldBuscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));

		jButtonBuscar.setIcon(new javax.swing.ImageIcon("src/Imagens/lupa.png")); // NOI18N
		jButtonBuscar.setBorder(null);
		jButtonBuscar.setBackground(new Color(0, 0, 0, 0));
		jButtonBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				try {
					jButtonBuscarMouseClicked(evt);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		jButtonAtualizar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
		jButtonAtualizar.setText("Atualizar");
		jButtonAtualizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
		jButtonAtualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
					jButtonAtualizarMouseClicked(evt);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });
		
		

		
		jLabelAtualizacaoMensagem.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
		jLabelAtualizacaoMensagem.setForeground(new java.awt.Color(102, 102, 102));
		jLabelAtualizacaoMensagem.setText("Atualizado pela última vez as " + LocalDateTime.now().format(hora));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(tela);
		tela.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(50, 50, 50)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(layout.createSequentialGroup().addGap(150, 150, 150)
										.addComponent(jScrollPane2).addGap(18, 18, 18).addComponent(jButtonMeuPerfil,
												javax.swing.GroupLayout.PREFERRED_SIZE, 111,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addComponent(
										jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING,
										javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
								.addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(layout.createSequentialGroup()
														.addComponent(jLabelTituloPagina,
																javax.swing.GroupLayout.PREFERRED_SIZE, 204,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(jTextFieldBuscar))
												.addGroup(layout.createSequentialGroup()
														.addComponent(jButtonAtualizar,
																javax.swing.GroupLayout.PREFERRED_SIZE, 85,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(18, 18, 18).addComponent(jLabelAtualizacaoMensagem,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jButtonBuscar)))
						.addGap(50, 50, 50)));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(82, 82, 82)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jButtonMeuPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(52, 52, 52)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(jButtonAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 31,
												Short.MAX_VALUE)
										.addComponent(jLabelAtualizacaoMensagem, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addGap(18, 18, 18)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 37,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabelTituloPagina,
														javax.swing.GroupLayout.PREFERRED_SIZE, 36,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE,
														37, javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
								.addContainerGap()));

		pack();
		getContentPane().add(tela);

	}// </editor-fold>//GEN-END:initComponents

	private void jButtonMeuPerfilActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {// GEN-FIRST:event_jButtonMeuPerfilActionPerformed
		MyProfileView.setUsuario(usuario);
		MyProfileView.setConect(conect);
		new MyProfileView();
		MyProfileView.main(null);
		this.dispose();
	}// GEN-LAST:event_jButtonMeuPerfilActionPerformed

	private void jButtonBuscarMouseClicked(java.awt.event.MouseEvent evt) throws SQLException {// GEN-FIRST:event_jButtonBuscarMouseClicked
		rcontroller = new RequestController();

		chamadosAbertos = rcontroller.searchInOpenRequests(conect, jTextFieldBuscar.getText(), usuario.getId_usuario(),
				usuario.getTipo_usuario());

		Object[][] ob = controller.generateObjectArray(chamadosAbertos);

		jTableColetasAbertas.setModel(new javax.swing.table.DefaultTableModel(ob,
				new String[] { "Código", "Nome da Escola", "Tipo de Lixo", "Data de Abertura" }) {
			Class[] types = new Class[] { java.lang.String.class, java.lang.String.class, java.lang.String.class,
					java.lang.String.class };
			boolean[] canEdit = new boolean[] { false, false, false, false };

			public Class getColumnClass(int columnIndex) {
				return types[columnIndex];
			}

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});

		jTableColetasAbertas.getColumnModel().getColumn(0).setPreferredWidth(100);
		jTableColetasAbertas.getColumnModel().getColumn(1).setPreferredWidth(900);
		jTableColetasAbertas.getColumnModel().getColumn(2).setPreferredWidth(300);
		jTableColetasAbertas.getColumnModel().getColumn(3).setPreferredWidth(100);

	}// GEN-LAST:event_jButtonBuscarMouseClicked

	private void jTableColetasAbertasMouseClicked(java.awt.event.MouseEvent evt) throws SQLException {
		rcontroller = new RequestController();

		chamado = rcontroller.createObjectRequest(conect,
				jTableColetasAbertas.getValueAt(jTableColetasAbertas.getSelectedRow(), 0).toString());
		RequestDetailsView.setUsuario(usuario);
		RequestDetailsView.setChamado(chamado);
		RequestDetailsView.setConect(conect);
		RequestDetailsView.setContexto(1);
		new RequestDetailsView();
		RequestDetailsView.main(null);
		this.dispose();

	}
	
	   private void jButtonAtualizarMouseClicked(java.awt.event.MouseEvent evt) throws SQLException {                                              
		   controller = new CollectorController();
		   jLabelAtualizacaoMensagem.setText("Atualizado pela última vez as " + LocalDateTime.now().format(hora));
		   chamadosAbertos = controller.getAllOpenRequests(conect);
			Object[][] ob = controller.generateObjectArray(chamadosAbertos);
			jTableColetasAbertas.setModel(new javax.swing.table.DefaultTableModel(ob,
					new String[] { "Código", "Nome da Escola", "Tipo de Lixo", "Data de Abertura" }) {
				Class[] types = new Class[] { java.lang.String.class, java.lang.String.class, java.lang.String.class,
						java.lang.String.class };
				boolean[] canEdit = new boolean[] { false, false, false, false };

				public Class getColumnClass(int columnIndex) {
					return types[columnIndex];
				}

				public boolean isCellEditable(int rowIndex, int columnIndex) {
					return canEdit[columnIndex];
				}
			});

			jTableColetasAbertas.getColumnModel().getColumn(0).setPreferredWidth(100);
			jTableColetasAbertas.getColumnModel().getColumn(1).setPreferredWidth(900);
			jTableColetasAbertas.getColumnModel().getColumn(2).setPreferredWidth(300);
			jTableColetasAbertas.getColumnModel().getColumn(3).setPreferredWidth(100);
	    }  

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(PageCollectorView.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(PageCollectorView.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(PageCollectorView.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(PageCollectorView.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					new PageCollectorView().setVisible(true);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButtonAtualizar;
	private javax.swing.JButton jButtonBuscar;
	private javax.swing.JButton jButtonMeuPerfil;
	private javax.swing.JLabel jLabelAtualizacaoMensagem;
	private javax.swing.JTextArea jLabelBemVindo;
	private javax.swing.JLabel jLabelTituloPagina;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTable jTableColetasAbertas;
	private javax.swing.JTextField jTextFieldBuscar;
	// End of variables declaration//GEN-END:variables
}
