/*

 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.ucsal.sage.request.view;

import java.awt.Color;
import java.awt.GridLayout;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;

import br.ucsal.sage.collector.view.PageCollectorView;
import br.ucsal.sage.request.controller.RequestController;
import br.ucsal.sage.request.model.Request;
import br.ucsal.sage.user.model.User;
import br.ucsal.sage.user.view.CanvasBackground;
import br.ucsal.sage.user.view.RequestOptionsView;

/**
 *
 * @author Suporte TI
 */
public class MyRequests extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    
    
    private CanvasBackground tela;
    private ArrayList <Request> meusChamados;
    private RequestController controller;
    private static User usuario;
    private static Connection conect;
    private static int contexto;
    private  String editHeader;
    
    public static void setUsuario(User u) {
    	usuario = u;
    }
    public static void setConect(Connection c) {
    	conect = c;
    }
    
    public static void setContexto(int i) {
    	contexto = i;
    }
    
    public MyRequests() throws SQLException {
        
        
        initComponents();
    	setExtendedState(MAXIMIZED_BOTH);
        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @throws SQLException 
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() throws SQLException {

    	setLayout(new GridLayout());
        tela = new CanvasBackground("src/Imagens/meu_perfil.png");
      jButtonVoltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMinhasColetas = new javax.swing.JTable();
        jLabelTituloPagina = new javax.swing.JLabel();
        jTextFieldBuscar = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxOpcaoOrdenar = new javax.swing.JComboBox<>();
        jButtonOrdenar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        controller = new RequestController();
        meusChamados = controller.findRequestByUser(conect, usuario.getId_usuario());
        Object[][] ob = controller.generateObjectArray(meusChamados, usuario.getTipo_usuario());
        
        editHeader = "";
        if(usuario.getTipo_usuario() == 1)
        	editHeader = "Nome coletor";
        else
        	editHeader = "Nome escola";

        jButtonVoltar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonVoltar.setForeground(new java.awt.Color(51, 153, 0));
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.setBorder(null);
        jButtonVoltar.setContentAreaFilled(false);
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					jButtonVoltarActionPerformed(evt);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        
        jScrollPane1.getViewport().setBackground(Color.WHITE);
        jScrollPane1.setBorder(null);

        jTableMinhasColetas.setBackground(new java.awt.Color(102, 204, 0));
        jTableMinhasColetas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTableMinhasColetas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTableMinhasColetas.setForeground(new java.awt.Color(255, 255, 255));
        jTableMinhasColetas.setModel(new javax.swing.table.DefaultTableModel(
           ob,
            new String [] {
                "Código", editHeader, "Tipo de Lixo", "Status", "Data de Abertura", "Data de Coleta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableMinhasColetas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableMinhasColetas.setGridColor(new java.awt.Color(255, 255, 255));
        jTableMinhasColetas.setSelectionBackground(new java.awt.Color(153, 255, 153));
        jTableMinhasColetas.setSelectionForeground(new java.awt.Color(102, 102, 102));
        jTableMinhasColetas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableMinhasColetas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableMinhasColetas.setShowGrid(true);
        jTableMinhasColetas.setRowHeight(50); 
        jTableMinhasColetas.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTableMinhasColetas.getColumnModel().getColumn(1).setPreferredWidth(700);
        jTableMinhasColetas.getColumnModel().getColumn(2).setPreferredWidth(400);
        jTableMinhasColetas.getColumnModel().getColumn(3).setPreferredWidth(200);
        jTableMinhasColetas.getColumnModel().getColumn(4).setPreferredWidth(120);
        jTableMinhasColetas.getColumnModel().getColumn(5).setPreferredWidth(120);
        jTableMinhasColetas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
					jTableMinhasColetasMouseClicked(evt);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });
        jScrollPane1.setViewportView(jTableMinhasColetas);

        jLabelTituloPagina.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelTituloPagina.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelTituloPagina.setText("Minhas coletas:");

        jTextFieldBuscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        jTextFieldBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscarActionPerformed(evt);
            }
        });

        jButtonBuscar.setIcon(new javax.swing.ImageIcon("src/Imagens/lupa.png")); // NOI18N
        jButtonBuscar.setBorder(null);
        jButtonBuscar.setBackground(new Color(0,0,0,0));
        jButtonBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
					jButtonBuscarMouseClicked(evt);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Ordenar por:");

      
        jComboBoxOpcaoOrdenar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jComboBoxOpcaoOrdenar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "status (crescente)", "status (decrescente)",  editHeader.toLowerCase() + " (crescente)",  editHeader.toLowerCase() + " (decresente)", "data de abertura (crescente)", "data de abertura (decresente)", "data de coleta (crescente)", "data de coleta (decresente)" }));

        jButtonOrdenar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonOrdenar.setText("Ordenar");
        jButtonOrdenar.setBackground(Color.WHITE);
        jButtonOrdenar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        jButtonOrdenar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonOrdenarMouseClicked(evt);
            }
        });
        jButtonOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					jButtonOrdenarActionPerformed(evt);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(tela);
        tela.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxOpcaoOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                        .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonBuscar))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTituloPagina, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelTituloPagina, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBuscar)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxOpcaoOrdenar)
                    .addComponent(jButtonOrdenar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        getContentPane().add(tela);
     
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButtonVoltarActionPerformed
       if(contexto == 1)
    	new RequestOptionsView().main(null);
       else
    	   new PageCollectorView().main(null);
        this.dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jTextFieldBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscarActionPerformed

    private void jButtonBuscarMouseClicked(java.awt.event.MouseEvent evt) throws SQLException {//GEN-FIRST:event_jButtonBuscarMouseClicked
    	
    	if(!jTextFieldBuscar.getText().replaceAll(" ", "").equals("")) {
    	controller = new RequestController();
    	if(usuario.getTipo_usuario() == 1)
    	meusChamados = controller.requesterSearch(conect, jTextFieldBuscar.getText(), usuario.getId_usuario());
    	
    	else
    	meusChamados = controller.collectorSearch(conect, jTextFieldBuscar.getText(), usuario.getId_usuario());
    	}else
    		meusChamados = controller.findRequestByUser(conect, usuario.getId_usuario());
    	Object[][] ob = controller.generateObjectArray(meusChamados, usuario.getTipo_usuario());
    	
    	
         jTableMinhasColetas.setModel(new javax.swing.table.DefaultTableModel(
            ob,
             new String [] {
                 "Código", editHeader, "Tipo de Lixo", "Status", "Data de Abertura", "Data de Coleta"
             }
         ) {
             Class[] types = new Class [] {
                 java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
             };
             boolean[] canEdit = new boolean [] {
                 false, false, false, false, false, false
             };

             public Class getColumnClass(int columnIndex) {
                 return types [columnIndex];
             }

             public boolean isCellEditable(int rowIndex, int columnIndex) {
                 return canEdit [columnIndex];
             }
         });
        
         jTableMinhasColetas.setRowHeight(50); 
         jTableMinhasColetas.getColumnModel().getColumn(0).setPreferredWidth(100);
         jTableMinhasColetas.getColumnModel().getColumn(1).setPreferredWidth(700);
         jTableMinhasColetas.getColumnModel().getColumn(2).setPreferredWidth(400);
         jTableMinhasColetas.getColumnModel().getColumn(3).setPreferredWidth(200);
         jTableMinhasColetas.getColumnModel().getColumn(4).setPreferredWidth(120);
         jTableMinhasColetas.getColumnModel().getColumn(5).setPreferredWidth(120);
         
    	
    }//GEN-LAST:event_jButtonBuscarMouseClicked

    private void jTableMinhasColetasMouseClicked(java.awt.event.MouseEvent evt) throws SQLException {//GEN-FIRST:event_jTableMinhasColetasMouseClicked
    	controller = new RequestController();
    	
    	Request chamado = controller.createObjectRequest(conect, jTableMinhasColetas.getValueAt(jTableMinhasColetas.getSelectedRow(), 0).toString());
    	RequestDetailsView.setUsuario(usuario);
    	RequestDetailsView.setChamado(chamado);
    	RequestDetailsView.setContexto(2);
    	RequestDetailsView.setConect(conect);
    	new RequestDetailsView().main(null);
    	this.dispose();
    }//GEN-LAST:event_jTableMinhasColetasMouseClicked

    private void jButtonOrdenarActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButtonOrdenarActionPerformed
        if(jComboBoxOpcaoOrdenar.getSelectedIndex() != 0) {
    	controller = new RequestController();
        
    	meusChamados = controller.organizeArray(meusChamados, jComboBoxOpcaoOrdenar.getSelectedIndex(), usuario.getTipo_usuario());
        Object[][] ob = controller.generateObjectArray(meusChamados, usuario.getTipo_usuario());
    	
   	 	

        jTableMinhasColetas.setModel(new javax.swing.table.DefaultTableModel(
           ob,
            new String [] {
                "Código", editHeader, "Tipo de Lixo", "Status", "Data de Abertura", "Data de Coleta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
       
        jTableMinhasColetas.setRowHeight(50); 
        jTableMinhasColetas.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTableMinhasColetas.getColumnModel().getColumn(1).setPreferredWidth(700);
        jTableMinhasColetas.getColumnModel().getColumn(2).setPreferredWidth(400);
        jTableMinhasColetas.getColumnModel().getColumn(3).setPreferredWidth(200);
        jTableMinhasColetas.getColumnModel().getColumn(4).setPreferredWidth(120);
        jTableMinhasColetas.getColumnModel().getColumn(5).setPreferredWidth(120);
        
        }
        
        }//GEN-LAST:event_jButtonOrdenarActionPerformed

    private void jButtonOrdenarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOrdenarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonOrdenarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyRequests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyRequests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyRequests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyRequests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
					new MyRequests().setVisible(true);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonOrdenar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<String> jComboBoxOpcaoOrdenar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelTituloPagina;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMinhasColetas;
    private javax.swing.JTextField jTextFieldBuscar;
    // End of variables declaration//GEN-END:variables
}
