/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.ucsal.sage.request.view;

import java.awt.Color;
import java.awt.GridLayout;
import java.sql.Connection;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

import br.ucsal.sage.collector.view.CompletedRequestView1;
import br.ucsal.sage.collector.view.PageCollectorView;
import br.ucsal.sage.collector.view.TakeRequestView1;
import br.ucsal.sage.request.controller.RequestController;
import br.ucsal.sage.request.model.Request;
import br.ucsal.sage.user.controller.UserController;
import br.ucsal.sage.user.model.User;
import br.ucsal.sage.user.view.CanvasBackground;

/**
 *
 * @author Suporte TI
 */
public class RequestDetailsView extends javax.swing.JFrame {

	/**
	 * Creates new form Solicitacao_Coleta_1
	 */
	private static Request chamado;
	private static int contexto;
	private static User usuario;
	private static Connection conect;
	private DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
	private UserController controller;
	private RequestController rcontroller;
	private CanvasBackground tela;

	public static void setContexto(int i) {
		contexto = i;
	}

	public static void setChamado(Request r) {
		chamado = r;
	}

	public static void setUsuario(User u) {
		usuario = u;
	}

	public static void setConect(Connection c) {
		conect = c;
	}

	public RequestDetailsView() throws SQLException {

		initComponents();
		setExtendedState(MAXIMIZED_BOTH);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 * 
	 * @throws SQLException
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() throws SQLException {

		setLayout(new GridLayout());
		tela = new CanvasBackground("src/Imagens/cadastro_2.png");

		jLabel2 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextAreaTituloPagina = new javax.swing.JTextArea();
		jLabelAbertura = new javax.swing.JLabel();
		jLabelTipoLixo = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabelDisponibilidade = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabelObservacao = new javax.swing.JLabel();
		jLabelTextoColetoraTelefone = new javax.swing.JLabel();
		jLabelColetoraTelefone = new javax.swing.JLabel();
		jLabelTextoData = new javax.swing.JLabel();
		jLabelData = new javax.swing.JLabel();
		jLabelTextoEndereco = new javax.swing.JLabel();
		jLabelEndereco = new javax.swing.JLabel();
		jLabelMensagemColetaRealizada = new javax.swing.JLabel();
		jLabelTextoMensagemCodigo = new javax.swing.JLabel();
		jLabelCodigoConfirmacao = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTextAreaTextoMensagemCodigo2 = new javax.swing.JTextArea();
		jButtonCancelar = new javax.swing.JButton();
		jButtonColetaRealizada = new javax.swing.JButton();
		jButtonAssumirColeta = new javax.swing.JButton();
		jButtonVoltar = new javax.swing.JButton();

		jLabel2.setText("jLabel2");

		jLabel1.setText("jLabel1");

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jScrollPane1.setBorder(null);

		jTextAreaTituloPagina.setEditable(false);
		jTextAreaTituloPagina.setBackground(new Color(0, 0, 0, 0));
		jTextAreaTituloPagina.setColumns(20);
		jTextAreaTituloPagina.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
		jTextAreaTituloPagina.setLineWrap(true);
		jTextAreaTituloPagina.setRows(3);
		jTextAreaTituloPagina.setText(chamado.getId_chamado() + " - " + chamado.getNome_escola());
		jTextAreaTituloPagina.setWrapStyleWord(true);
		jTextAreaTituloPagina.setBorder(null);
		jTextAreaTituloPagina.setOpaque(false);
		jScrollPane1.setViewportView(jTextAreaTituloPagina);

		jScrollPane1.getViewport().setBackground(new Color(0, 0, 0, 0));
		jScrollPane2.getViewport().setBackground(new Color(0, 0, 0, 0));

		jLabelAbertura.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
		jLabelAbertura.setForeground(new java.awt.Color(102, 102, 102));
		jLabelAbertura.setText("Chamado aberto em " + formatter.format(LocalDate.parse(chamado.getData_abertura()))
				+ " as " + chamado.getHora_abertura());

		jLabelTipoLixo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		jLabelTipoLixo.setText(chamado.getTipo_lixo());

		jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		jLabel3.setText("Tipos de lixo:");

		jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		jLabel4.setText("Disponibilidade:");

		jLabelDisponibilidade.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		jLabelDisponibilidade.setText(chamado.getDisponibilidade());

		jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		jLabel5.setText("Observações:");

		jLabelObservacao.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		jLabelObservacao.setText(chamado.getSobre_chamado());

		jLabelTextoColetoraTelefone.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

		jLabelColetoraTelefone.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

		jLabelTextoData.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

		jLabelData.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

		jLabelTextoEndereco.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		jLabelTextoEndereco.setText("Endereço:");

		jLabelEndereco.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

		jLabelMensagemColetaRealizada.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
		jLabelMensagemColetaRealizada.setForeground(new java.awt.Color(51, 204, 0));

		jLabelTextoMensagemCodigo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		jLabelTextoMensagemCodigo.setForeground(new java.awt.Color(102, 102, 102));
		jLabelTextoMensagemCodigo.setText("Código de confirmação de coleta:");

		jLabelCodigoConfirmacao.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		jLabelCodigoConfirmacao.setForeground(new java.awt.Color(102, 102, 102));
		jLabelCodigoConfirmacao.setText("jLabel6");

		jScrollPane2.setBackground(new Color(0, 0, 0, 0));
		jScrollPane2.setBorder(null);

		jTextAreaTextoMensagemCodigo2.setEditable(false);
		jTextAreaTextoMensagemCodigo2.setColumns(20);
		jTextAreaTextoMensagemCodigo2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
		jTextAreaTextoMensagemCodigo2.setForeground(new java.awt.Color(102, 102, 102));
		jTextAreaTextoMensagemCodigo2.setLineWrap(true);
		jTextAreaTextoMensagemCodigo2.setRows(2);
		jTextAreaTextoMensagemCodigo2
				.setText("Esse código serve para validar a coleta. Só informe ao coletor após a realização da coleta.");
		jTextAreaTextoMensagemCodigo2.setWrapStyleWord(true);
		jTextAreaTextoMensagemCodigo2.setBorder(null);
		jTextAreaTextoMensagemCodigo2.setOpaque(false);
		jTextAreaTextoMensagemCodigo2.setBackground(new Color(0, 0, 0, 0));
		jScrollPane2.setViewportView(jTextAreaTextoMensagemCodigo2);

		jButtonCancelar.setBackground(new java.awt.Color(51, 204, 0));
		jButtonCancelar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
		jButtonCancelar.setForeground(new java.awt.Color(255, 255, 255));
		jButtonCancelar.setText("Cancelar");
		jButtonCancelar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 51), 2, true));
		jButtonCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				try {
					jButtonCancelarMouseClicked(evt);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		jButtonColetaRealizada.setBackground(new java.awt.Color(51, 204, 0));
		jButtonColetaRealizada.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
		jButtonColetaRealizada.setForeground(new java.awt.Color(255, 255, 255));
		jButtonColetaRealizada.setText("Coleta realizada");
		jButtonColetaRealizada.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 51), 2, true));
		jButtonColetaRealizada.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButtonColetaRealizadaMouseClicked(evt);
			}
		});

		jButtonAssumirColeta.setBackground(new java.awt.Color(51, 204, 0));
		jButtonAssumirColeta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
		jButtonAssumirColeta.setForeground(new java.awt.Color(255, 255, 255));
		jButtonAssumirColeta.setText("Assumir coleta");
		jButtonAssumirColeta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 51), 2, true));
		jButtonAssumirColeta.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButtonAssumirColetaMouseClicked(evt);
			}
		});
		

		jButtonVoltar.setBackground(new Color(0, 0, 0, 0));
		jButtonVoltar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
		jButtonVoltar.setText("Voltar");
		jButtonVoltar.setBorder(null);
		jButtonVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				try {
					jButtonVoltarMouseClicked(evt);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(tela);
		tela.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addGap(50, 50, 50).addGroup(layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
												.createSequentialGroup()
												.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1205,
														Short.MAX_VALUE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE,
														153, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addComponent(
												jLabelMensagemColetaRealizada, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGroup(layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
												.addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE,
														153, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(18, 18,
														18)
												.addComponent(jButtonColetaRealizada,
														javax.swing.GroupLayout.PREFERRED_SIZE, 153,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(0, 0, Short.MAX_VALUE))
										.addGroup(layout.createSequentialGroup().addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
												.addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jLabelTextoData,
														javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
												.addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jLabelTextoColetoraTelefone,
														javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(
														jLabelTextoEndereco, javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
																.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
																.addGroup(layout.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(jScrollPane2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				393,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGroup(layout.createSequentialGroup()
																				.addComponent(jLabelTextoMensagemCodigo)
																				.addPreferredGap(
																						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(jLabelCodigoConfirmacao,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						116,
																						javax.swing.GroupLayout.PREFERRED_SIZE))))
														.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
																.createSequentialGroup().addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(layout.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(jLabelEndereco,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(jLabelTipoLixo,
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(jLabelObservacao,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(
																				jLabelColetoraTelefone,
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(jLabelData,
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)))))))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
										.addGap(268, 268, 268)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabelAbertura,
														javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.PREFERRED_SIZE, 400,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabelDisponibilidade,
														javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
						.addGap(30, 30, 30))
				.addGroup(layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jButtonAssumirColeta, javax.swing.GroupLayout.PREFERRED_SIZE, 153,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(50, 50, 50)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18).addComponent(jLabelAbertura).addGap(26, 26, 26)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabelTipoLixo, javax.swing.GroupLayout.PREFERRED_SIZE, 22,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel3))
						.addGap(18, 19, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabelDisponibilidade, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGap(18, 21, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabelObservacao, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGap(18, 21, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jLabelTextoColetoraTelefone, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabelColetoraTelefone, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGap(18, 21, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabelTextoEndereco).addComponent(jLabelEndereco,
										javax.swing.GroupLayout.PREFERRED_SIZE, 22,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 21, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabelTextoData, javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(jLabelData, javax.swing.GroupLayout.Alignment.TRAILING,
										javax.swing.GroupLayout.PREFERRED_SIZE, 22,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabelMensagemColetaRealizada)
								.addComponent(jLabelTextoMensagemCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 24,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabelCodigoConfirmacao, javax.swing.GroupLayout.PREFERRED_SIZE, 25,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jButtonColetaRealizada, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jButtonAssumirColeta, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(100, 100, 100)));

		pack();
		getContentPane().add(tela);

		editarVisualizacao();
	}// </editor-fold>//GEN-END:initComponents

	private void jButtonVoltarMouseClicked(java.awt.event.MouseEvent evt) throws SQLException {// GEN-FIRST:event_jButtonVoltarMouseClicked
		this.dispose();
		if (contexto == 1)
			new PageCollectorView().main(null);
		else
			new MyRequests().main(null);

	}// GEN-LAST:event_jButtonVoltarMouseClicked

	private void jButtonCancelarMouseClicked(java.awt.event.MouseEvent evt) throws SQLException {// GEN-FIRST:event_jButtonCancelarMouseClicked
		this.dispose();
		rcontroller = new RequestController();
		if (usuario.getTipo_usuario() == 1)
			rcontroller.cancelRequest(conect, chamado.getId_chamado());
		else
			rcontroller.cancelCollect(conect, chamado.getId_chamado());

		Request atualizado = rcontroller.createObjectRequest(conect, chamado.getId_chamado());
		RequestDetailsView.setChamado(atualizado);
		new RequestDetailsView().main(null);

	}// GEN-LAST:event_jButtonCancelarMouseClicked

	private void jButtonColetaRealizadaMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jButtonColetaRealizadaMouseClicked
		this.dispose();
		CompletedRequestView1.setConect(conect);
		CompletedRequestView1.setChamado(chamado);
		new CompletedRequestView1().main(null);

	}// GEN-LAST:event_jButtonColetaRealizadaMouseClicked

	private void jButtonAssumirColetaMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jButtonAssumirColetaMouseClicked
		this.dispose();
		TakeRequestView1.setUsuario(usuario);
		TakeRequestView1.setChamado(chamado);
		TakeRequestView1.setConect(conect);
		new TakeRequestView1().main(null);

	}// GEN-LAST:event_jButtonAssumirColetaMouseClicked

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(RequestDetailsView.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(RequestDetailsView.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(RequestDetailsView.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(RequestDetailsView.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					new RequestDetailsView().setVisible(true);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});
	}

	public void editarVisualizacao() throws SQLException {
		if (usuario.getTipo_usuario() == 1) {

			jButtonAssumirColeta.setVisible(false);
			jButtonColetaRealizada.setVisible(false);
			jLabelTextoEndereco.setVisible(false);
			jLabelEndereco.setVisible(false);

			jLabelColetoraTelefone.setText(chamado.getNome_coletor());
			jLabelTextoColetoraTelefone.setText("Coletora responsável:");

			jLabelCodigoConfirmacao.setText(chamado.getCodigo_verificacao());

			if (chamado.getStatus_int() == 1 || chamado.getStatus_int() == 2) {
				jButtonCancelar.setText("Cancelar Solicitação");
				if(chamado.getPrevisao_coleta().equals("-"))
					jLabelData.setText("-");
				else
				jLabelData.setText(formatter.format(LocalDate.parse(chamado.getPrevisao_coleta())));
				
				jLabelTextoData.setText("Data prevista de coleta:");
			} else if (chamado.getStatus_int() == 5) {
				jButtonCancelar.setVisible(false);
				jLabelMensagemColetaRealizada.setText("Cancelado");
				if (chamado.getData_coleta().equals("-"))
					jLabelData.setText("-");
				else
					jLabelData.setText(formatter.format(LocalDate.parse(chamado.getData_coleta())));
				jLabelTextoData.setText("Data prevista de coleta:");
			} else if (chamado.getStatus_int() == 3) {
				jButtonCancelar.setVisible(false);
				jLabelMensagemColetaRealizada.setText("Coleta realizada!");
				jLabelData.setText(formatter.format(LocalDate.parse(chamado.getData_coleta())));
				jLabelTextoData.setText("Data de coleta:");
			}

		} else {
			controller = new UserController();
			jLabelTextoMensagemCodigo.setVisible(false);
			jTextAreaTextoMensagemCodigo2.setVisible(false);
			jLabelCodigoConfirmacao.setVisible(false);
			User escola = controller.getUserDataById(conect, chamado.getId_escola());
			jLabelEndereco.setText(escola.getEndereco());
			jLabelTextoColetoraTelefone.setText("Telefone:");
			jLabelColetoraTelefone.setText(escola.getTelefone() + " / " + escola.getCelular());
			if (chamado.getStatus_int() == 1) {
				jButtonCancelar.setVisible(false);
				jButtonColetaRealizada.setVisible(false);
			}

			else if (chamado.getStatus_int() == 2) {
				jButtonAssumirColeta.setVisible(false);
				jButtonCancelar.setText("Cancelar coleta");
				jLabelData.setText(formatter.format(LocalDate.parse(chamado.getPrevisao_coleta())));
				jLabelTextoData.setText("Data prevista para coleta:");
			} else if (chamado.getStatus_int() == 3) {
				jLabelMensagemColetaRealizada.setText("Coleta realizada!");
				jButtonAssumirColeta.setVisible(false);
				jButtonColetaRealizada.setVisible(false);
				jButtonCancelar.setVisible(false);
				jLabelData.setText(formatter.format(LocalDate.parse(chamado.getData_coleta())));
				jLabelTextoData.setText("Data de coleta:");

			} else if (chamado.getStatus_int() == 5) {
				jButtonAssumirColeta.setVisible(false);
				jButtonColetaRealizada.setVisible(false);
				jButtonCancelar.setVisible(false);
				jLabelMensagemColetaRealizada.setText("Cancelado");
				jLabelData.setText(formatter.format(LocalDate.parse(chamado.getPrevisao_coleta())));
				jLabelTextoData.setText("Data prevista para coleta:");
			}
		}
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButtonAssumirColeta;
	private javax.swing.JButton jButtonCancelar;
	private javax.swing.JButton jButtonColetaRealizada;
	private javax.swing.JButton jButtonVoltar;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabelAbertura;
	private javax.swing.JLabel jLabelCodigoConfirmacao;
	private javax.swing.JLabel jLabelColetoraTelefone;
	private javax.swing.JLabel jLabelData;
	private javax.swing.JLabel jLabelDisponibilidade;
	private javax.swing.JLabel jLabelEndereco;
	private javax.swing.JLabel jLabelMensagemColetaRealizada;
	private javax.swing.JLabel jLabelObservacao;
	private javax.swing.JLabel jLabelTextoColetoraTelefone;
	private javax.swing.JLabel jLabelTextoData;
	private javax.swing.JLabel jLabelTextoEndereco;
	private javax.swing.JLabel jLabelTextoMensagemCodigo;
	private javax.swing.JLabel jLabelTipoLixo;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTextArea jTextAreaTextoMensagemCodigo2;
	private javax.swing.JTextArea jTextAreaTituloPagina;
	// End of variables declaration//GEN-END:variables
}
