/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.ucsal.sage.requester.view;

import java.awt.GridLayout;
import java.sql.Connection;
import java.sql.SQLException;

import br.ucsal.sage.request.model.Request;
import br.ucsal.sage.user.view.CanvasBackground;

/**
 *
 * @author Suporte TI
 */
public class CreateRequestView1 extends javax.swing.JFrame {

    /**
     * Creates new form Solicitacao_Coleta_1
     */
	
	private Request chamado;
	private static String id_usuario;
	 private static Connection conect;
	 private  CanvasBackground tela;
	    
	    public static void setConect(Connection c) {
	    	conect = c;
	    }
	
	public static void setIdUsuario(String s) {
		id_usuario = s;
	}
	
    
   
    public CreateRequestView1() {
        
        initComponents();
    setExtendedState(MAXIMIZED_BOTH);
       
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	 setLayout(new GridLayout());
    	    tela = new CanvasBackground("src/Imagens/cadastro_1.png");
    	    
    	      jLabel1 = new javax.swing.JLabel();
    	        jCheckBoxEletronico = new javax.swing.JCheckBox();
    	        jButtonProximo = new javax.swing.JButton();
    	        jButtonAnterior = new javax.swing.JButton();

    	        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    	        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
    	        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    	        jLabel1.setText("Informe os tipos de lixo:");

    	        jCheckBoxEletronico.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
    	        jCheckBoxEletronico.setText("Eletrônico");
    	        jCheckBoxEletronico.addActionListener(new java.awt.event.ActionListener() {
    	            public void actionPerformed(java.awt.event.ActionEvent evt) {
    	                jCheckBoxEletronicoActionPerformed(evt);
    	            }
    	        });

    	        jButtonProximo.setBackground(new java.awt.Color(51, 204, 0));
    	        jButtonProximo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    	        jButtonProximo.setForeground(new java.awt.Color(255, 255, 255));
    	        jButtonProximo.setText("Próximo");
    	        jButtonProximo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 3, true));
    	        jButtonProximo.addMouseListener(new java.awt.event.MouseAdapter() {
    	            public void mouseClicked(java.awt.event.MouseEvent evt) {
    	                jButtonProximoMouseClicked(evt);
    	            }
    	        });
    	        jButtonProximo.addActionListener(new java.awt.event.ActionListener() {
    	            public void actionPerformed(java.awt.event.ActionEvent evt) {
    	                jButtonProximoActionPerformed(evt);
    	            }
    	        });
    	        jButtonProximo.setVisible(false);

    	        jButtonAnterior.setBackground(new java.awt.Color(51, 204, 0));
    	        jButtonAnterior.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    	        jButtonAnterior.setForeground(new java.awt.Color(255, 255, 255));
    	        jButtonAnterior.setText("Anterior");
    	        jButtonAnterior.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 3, true));
    	        jButtonAnterior.addMouseListener(new java.awt.event.MouseAdapter() {
    	            public void mouseClicked(java.awt.event.MouseEvent evt) {
    	                try {
							jButtonAnteriorMouseClicked(evt);
						} catch (SQLException e) {
							// TODO Auto-generated catch block
							e.printStackTrace();
						}
    	            }
    	        });
    	        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
    	            public void actionPerformed(java.awt.event.ActionEvent evt) {
    	                jButtonAnteriorActionPerformed(evt);
    	            }
    	        });

    	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(tela);
    	       tela.setLayout(layout);
    	layout.setHorizontalGroup(
    	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    	            .addGroup(layout.createSequentialGroup()
    	                .addContainerGap(44, Short.MAX_VALUE)
    	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    	                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
    	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    	                            .addComponent(jLabel1)
    	                            .addComponent(jCheckBoxEletronico, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
    	                        .addGap(200, 200, 200))
    	                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
    	                        .addComponent(jButtonAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
    	                        .addGap(18, 18, 18)
    	                        .addComponent(jButtonProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
    	                        .addGap(100, 100, 100))))
    	        );
    	        layout.setVerticalGroup(
    	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    	            .addGroup(layout.createSequentialGroup()
    	                .addGap(250, 250, 250)
    	                .addComponent(jLabel1)
    	                .addGap(27, 27, 27)
    	                .addComponent(jCheckBoxEletronico)
    	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
    	                    .addComponent(jButtonAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
    	                    .addComponent(jButtonProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
    	                .addGap(36, 36, 36))
    	        );

    	        pack();
    	        getContentPane().add(tela);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxEletronicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxEletronicoActionPerformed
       if(jCheckBoxEletronico.isSelected())
    	jButtonProximo.setVisible(true);
       else
    	   jButtonProximo.setVisible(false);
    }//GEN-LAST:event_jCheckBoxEletronicoActionPerformed

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonAnteriorMouseClicked(java.awt.event.MouseEvent evt) throws SQLException {//GEN-FIRST:event_jButtonAnteriorMouseClicked
        new PageRequesterView().main(null);
        this.dispose();
    }//GEN-LAST:event_jButtonAnteriorMouseClicked

    private void jButtonProximoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonProximoMouseClicked
        this.chamado = new Request();
    	this.chamado.setTipo_lixo(jCheckBoxEletronico.getText());
        this.chamado.setId_escola(id_usuario);
        
        CreateRequestView2.setChamado(chamado);
        CreateRequestView2.setConect(conect);
        new CreateRequestView2().main(null);
        this.dispose();
        
    }//GEN-LAST:event_jButtonProximoMouseClicked

    private void jButtonProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProximoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonProximoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateRequestView1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateRequestView1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateRequestView1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateRequestView1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateRequestView1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonProximo;
    private javax.swing.JCheckBox jCheckBoxEletronico;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
