/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.ucsal.sage.requester.view;

import java.awt.GridLayout;
import java.sql.Connection;

import br.ucsal.sage.request.controller.RequestController;
import br.ucsal.sage.request.model.Request;
import br.ucsal.sage.user.view.CanvasBackground;

/**
 *
 * @author Suporte TI
 */
public class CreateRequestView3 extends javax.swing.JFrame {

    /**
     * Creates new form Solicitacao_Coleta_1
     */
    
    private CanvasBackground tela;
    private static Request chamado;
    private RequestController controller;
    
 private static Connection conect;
    
    public static void setConect(Connection c) {
    	conect = c;
    }
    
    public static void setChamado(Request r) {
    	chamado = r;
    }
    public CreateRequestView3() {
        
        initComponents();
    setExtendedState(MAXIMIZED_BOTH);
      
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	  setLayout(new GridLayout());
    	    tela = new CanvasBackground("src/Imagens/cadastro_1.png");
    	    
    	 jButtonProximo = new javax.swing.JButton();
    	        jButtonAnterior = new javax.swing.JButton();
    	        jScrollPane1 = new javax.swing.JScrollPane();
    	        jTextArea1 = new javax.swing.JTextArea();
    	        jLabel1 = new javax.swing.JLabel();
    	        jComboBoxHoraInicio = new javax.swing.JComboBox<>();
    	        jComboBoxMinutoInicio = new javax.swing.JComboBox<>();
    	        jLabel2 = new javax.swing.JLabel();
    	        jLabel3 = new javax.swing.JLabel();
    	        jComboBoxHoraFim = new javax.swing.JComboBox<>();
    	        jComboBoxMinutoFim = new javax.swing.JComboBox<>();
    	        jLabel4 = new javax.swing.JLabel();
    	        jLabelAvisoErro = new javax.swing.JLabel();

    	        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    	        jButtonProximo.setBackground(new java.awt.Color(51, 204, 0));
    	        jButtonProximo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    	        jButtonProximo.setForeground(new java.awt.Color(255, 255, 255));
    	        jButtonProximo.setText("Próximo");
    	        jButtonProximo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 3, true));
    	        jButtonProximo.addMouseListener(new java.awt.event.MouseAdapter() {
    	            public void mouseClicked(java.awt.event.MouseEvent evt) {
    	                jButtonProximoMouseClicked(evt);
    	            }
    	        });
    	        jButtonProximo.addActionListener(new java.awt.event.ActionListener() {
    	            public void actionPerformed(java.awt.event.ActionEvent evt) {
    	                jButtonProximoActionPerformed(evt);
    	            }
    	        });

    	        jButtonAnterior.setBackground(new java.awt.Color(51, 204, 0));
    	        jButtonAnterior.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    	        jButtonAnterior.setForeground(new java.awt.Color(255, 255, 255));
    	        jButtonAnterior.setText("Anterior");
    	        jButtonAnterior.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 3, true));
    	        jButtonAnterior.addMouseListener(new java.awt.event.MouseAdapter() {
    	            public void mouseClicked(java.awt.event.MouseEvent evt) {
    	                jButtonAnteriorMouseClicked(evt);
    	            }
    	        });
    	        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
    	            public void actionPerformed(java.awt.event.ActionEvent evt) {
    	                jButtonAnteriorActionPerformed(evt);
    	            }
    	        });

    	        jScrollPane1.setBorder(null);

    	        jTextArea1.setEditable(false);
    	        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
    	        jTextArea1.setColumns(10);
    	        jTextArea1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
    	        jTextArea1.setLineWrap(true);
    	        jTextArea1.setRows(2);
    	        jTextArea1.setTabSize(5);
    	        jTextArea1.setText("Informe horário de \npreferência de coleta:");
    	        jTextArea1.setBorder(null);
    	        jTextArea1.setOpaque(false);
    	        jTextArea1.setSelectedTextColor(new java.awt.Color(0, 0, 0));
    	        jTextArea1.setSelectionColor(new java.awt.Color(255, 255, 255));
    	        jScrollPane1.setViewportView(jTextArea1);

    	        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
    	        jLabel1.setText("De:");

    	        jComboBoxHoraInicio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    	        jComboBoxHoraInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
    	       

    	        jComboBoxMinutoInicio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    	        jComboBoxMinutoInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
    	        

    	        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
    	        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    	        jLabel2.setText(":");

    	        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
    	        jLabel3.setText("Até:");

    	        jComboBoxHoraFim.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    	        jComboBoxHoraFim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
    	      

    	        jComboBoxMinutoFim.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    	        jComboBoxMinutoFim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
    	       

    	        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
    	        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    	        jLabel4.setText(":");
    	        
    	        jLabelAvisoErro.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
    	        jLabelAvisoErro.setForeground(new java.awt.Color(255, 0, 0));
    	        jLabelAvisoErro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

    	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(tela);
    	        tela.setLayout(layout);
    	        layout.setHorizontalGroup(
    	                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    	                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
    	                    .addContainerGap(67, Short.MAX_VALUE)
    	                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    	                        .addGroup(layout.createSequentialGroup()
    	                            .addComponent(jComboBoxHoraFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    	                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    	                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
    	                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    	                            .addComponent(jComboBoxMinutoFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    	                        .addGroup(layout.createSequentialGroup()
    	                            .addComponent(jComboBoxHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    	                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    	                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
    	                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    	                            .addComponent(jComboBoxMinutoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    	                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
    	                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
    	                                .addGap(200, 200, 200))
    	                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
    	                                .addComponent(jButtonAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
    	                                .addGap(18, 18, 18)
    	                                .addComponent(jButtonProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
    	                                .addGap(100, 100, 100)))
    	                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
    	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
    	                            .addComponent(jLabelAvisoErro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    	                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE))))
    	            );
    	            layout.setVerticalGroup(
    	                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    	                .addGroup(layout.createSequentialGroup()
    	                    .addGap(250, 250, 250)
    	                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    	                    .addGap(34, 34, 34)
    	                    .addComponent(jLabel1)
    	                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
    	                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
    	                        .addComponent(jComboBoxHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
    	                        .addComponent(jComboBoxMinutoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
    	                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
    	                    .addGap(27, 27, 27)
    	                    .addComponent(jLabel3)
    	                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
    	                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
    	                        .addComponent(jComboBoxHoraFim, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
    	                        .addComponent(jComboBoxMinutoFim, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
    	                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
    	                    .addGap(74, 74, 74)
    	                    .addComponent(jLabelAvisoErro, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
    	                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
    	                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
    	                        .addComponent(jButtonAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
    	                        .addComponent(jButtonProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
    	                    .addGap(50, 50, 50))
    	            );

    	            pack();
    	        getContentPane().add(tela);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonAnteriorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAnteriorMouseClicked
        new CreateRequestView2().main(null);
        this.dispose();
    }//GEN-LAST:event_jButtonAnteriorMouseClicked

    private void jButtonProximoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonProximoMouseClicked
       System.out.println();
    	
    	if(jComboBoxHoraInicio.getSelectedIndex() != 0 && jComboBoxMinutoInicio.getSelectedIndex() != 0  && jComboBoxHoraFim.getSelectedIndex() != 0  && jComboBoxMinutoFim.getSelectedIndex() != 0) {
    	
    	controller = new RequestController();
        
       if(controller.validateHour(jComboBoxHoraInicio.getSelectedItem() + "" + jComboBoxMinutoInicio.getSelectedItem(), jComboBoxHoraFim.getSelectedItem() + "" + jComboBoxMinutoFim.getSelectedItem())) {
        chamado.setDisponibilidade(chamado.getDisponibilidade() + jComboBoxHoraInicio.getSelectedItem() + ":" + jComboBoxMinutoInicio.getSelectedItem() + " até " + jComboBoxHoraFim.getSelectedItem() + ":" + jComboBoxMinutoFim.getSelectedItem());
        CreateRequestView4.setChamado(chamado);
        CreateRequestView4.setConect(conect);
        new CreateRequestView4().main(null);
        this.dispose();
        }else
        	jLabelAvisoErro.setText("A hora de ínicio não pode ser maior que a hora de fim.");
    	}else
    		jLabelAvisoErro.setText("Preencha todos os campos.");
    }//GEN-LAST:event_jButtonProximoMouseClicked

    private void jButtonProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProximoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonProximoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateRequestView3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateRequestView3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateRequestView3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateRequestView3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateRequestView3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonProximo;
    private javax.swing.JComboBox<String> jComboBoxHoraFim;
    private javax.swing.JComboBox<String> jComboBoxHoraInicio;
    private javax.swing.JComboBox<String> jComboBoxMinutoFim;
    private javax.swing.JComboBox<String> jComboBoxMinutoInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelAvisoErro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
