/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.ucsal.sage.requester.view;

import java.awt.GridLayout;
import java.sql.SQLException;

import br.ucsal.sage.user.view.CanvasBackground;

/**
 *
 * @author Suporte TI
 */
public class CreateRequestView6 extends javax.swing.JFrame {

    /**
     * Creates new form Solicitacao_Coleta_1
     */
    
    private CanvasBackground tela;
    public CreateRequestView6() {
        
        initComponents();
    setExtendedState(MAXIMIZED_BOTH);
      
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	  setLayout(new GridLayout());
    	    tela = new CanvasBackground("src/Imagens/coletas.png");
    	    
    	 jButtonPaginaInicial = new javax.swing.JButton();
    	        jButtonAbrirChamado = new javax.swing.JButton();
    	        jScrollPane1 = new javax.swing.JScrollPane();
    	        jTextAreaProtocolo = new javax.swing.JTextArea();

    	        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    	        jButtonPaginaInicial.setBackground(new java.awt.Color(51, 204, 0));
    	        jButtonPaginaInicial.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    	        jButtonPaginaInicial.setForeground(new java.awt.Color(255, 255, 255));
    	        jButtonPaginaInicial.setText("Página Inicial");
    	        jButtonPaginaInicial.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 3, true));
    	        jButtonPaginaInicial.addMouseListener(new java.awt.event.MouseAdapter() {
    	            public void mouseClicked(java.awt.event.MouseEvent evt) {
    	                try {
							jButtonPaginaInicialMouseClicked(evt);
						} catch (SQLException e) {
							// TODO Auto-generated catch block
							e.printStackTrace();
						}
    	            }
    	        });
    	        jButtonPaginaInicial.addActionListener(new java.awt.event.ActionListener() {
    	            public void actionPerformed(java.awt.event.ActionEvent evt) {
    	                jButtonPaginaInicialActionPerformed(evt);
    	            }
    	        });

    	        jButtonAbrirChamado.setBackground(new java.awt.Color(51, 204, 0));
    	        jButtonAbrirChamado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    	        jButtonAbrirChamado.setForeground(new java.awt.Color(255, 255, 255));
    	        jButtonAbrirChamado.setText("Novo chamado");
    	        jButtonAbrirChamado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 3, true));
    	        jButtonAbrirChamado.addMouseListener(new java.awt.event.MouseAdapter() {
    	            public void mouseClicked(java.awt.event.MouseEvent evt) {
    	                jButtonAbrirChamadoMouseClicked(evt);
    	            }
    	        });
    	        jButtonAbrirChamado.addActionListener(new java.awt.event.ActionListener() {
    	            public void actionPerformed(java.awt.event.ActionEvent evt) {
    	                jButtonAbrirChamadoActionPerformed(evt);
    	            }
    	        });

    	        jScrollPane1.setBorder(null);

    	        jTextAreaProtocolo.setEditable(false);
    	        jTextAreaProtocolo.setBackground(new java.awt.Color(255, 255, 255));
    	        jTextAreaProtocolo.setColumns(10);
    	        jTextAreaProtocolo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
    	        jTextAreaProtocolo.setForeground(new java.awt.Color(51, 204, 0));
    	        jTextAreaProtocolo.setLineWrap(true);
    	        jTextAreaProtocolo.setRows(2);
    	        jTextAreaProtocolo.setTabSize(5);
    	        jTextAreaProtocolo.setText("Solicitação realizada com sucesso!");
    	        jTextAreaProtocolo.setBorder(null);
    	        jTextAreaProtocolo.setOpaque(false);
    	        jTextAreaProtocolo.setSelectedTextColor(new java.awt.Color(0, 0, 0));
    	        jTextAreaProtocolo.setSelectionColor(new java.awt.Color(255, 255, 255));
    	        jScrollPane1.setViewportView(jTextAreaProtocolo);

    	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(tela);
    	       tela.setLayout(layout);
    	 layout.setHorizontalGroup(
    	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    	            .addGroup(layout.createSequentialGroup()
    	                .addContainerGap(355, Short.MAX_VALUE)
    	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    	                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
    	                    .addGroup(layout.createSequentialGroup()
    	                        .addGap(47, 47, 47)
    	                        .addComponent(jButtonAbrirChamado, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
    	                        .addGap(30, 30, 30)
    	                        .addComponent(jButtonPaginaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
    	                .addGap(100, 100, 100))
    	        );
    	        layout.setVerticalGroup(
    	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    	            .addGroup(layout.createSequentialGroup()
    	                .addGap(250, 250, 250)
    	                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    	                .addGap(191, 191, 191)
    	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
    	                    .addComponent(jButtonAbrirChamado, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
    	                    .addComponent(jButtonPaginaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
    	                .addContainerGap(45, Short.MAX_VALUE))
    	        );

    	        pack();
    	        getContentPane().add(tela);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAbrirChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirChamadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAbrirChamadoActionPerformed

    private void jButtonAbrirChamadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAbrirChamadoMouseClicked
        new CreateRequestView1().main(null);
        this.dispose();
    }//GEN-LAST:event_jButtonAbrirChamadoMouseClicked

    private void jButtonPaginaInicialMouseClicked(java.awt.event.MouseEvent evt) throws SQLException {//GEN-FIRST:event_jButtonPaginaInicialMouseClicked
        new PageRequesterView().main(null);
        this.dispose();
    }//GEN-LAST:event_jButtonPaginaInicialMouseClicked

    private void jButtonPaginaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPaginaInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPaginaInicialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateRequestView6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateRequestView6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateRequestView6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateRequestView6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateRequestView6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbrirChamado;
    private javax.swing.JButton jButtonPaginaInicial;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaProtocolo;
    // End of variables declaration//GEN-END:variables
}
