/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.ucsal.sage.requester.view;

import java.awt.GridLayout;
import java.sql.Connection;

import br.ucsal.sage.request.model.Request;
import br.ucsal.sage.user.view.CanvasBackground;

/**
 *
 * @author Suporte TI
 */
public class CreateRequestView2 extends javax.swing.JFrame {

    /**
     * Creates new form Solicitacao_Coleta_1
     */
    private static Request chamado;
    
    private CanvasBackground tela;
 private static Connection conect;
    
    public static void setConect(Connection c) {
    	conect = c;
    }
    
    public static void setChamado(Request r) {
    	chamado = r;
    }
    public CreateRequestView2() {
        initComponents();
        
    setExtendedState(MAXIMIZED_BOTH);
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	setLayout(new GridLayout());
        tela = new CanvasBackground("src/Imagens/cadastro_1.png");
        
       jCheckBoxSegunda = new javax.swing.JCheckBox();
            jButtonProximo = new javax.swing.JButton();
            jButtonAnterior = new javax.swing.JButton();
            jScrollPane1 = new javax.swing.JScrollPane();
            jTextArea1 = new javax.swing.JTextArea();
            jCheckBoxTerca = new javax.swing.JCheckBox();
            jCheckBoxQuarta = new javax.swing.JCheckBox();
            jCheckBoxQuinta = new javax.swing.JCheckBox();
            jCheckBoxSexta = new javax.swing.JCheckBox();
            jCheckBoxSabado = new javax.swing.JCheckBox();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            jCheckBoxSegunda.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
            jCheckBoxSegunda.setText("Segunda-feira");
            jCheckBoxSegunda.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jCheckBoxSegundaActionPerformed(evt);
                }
            });

            jButtonProximo.setBackground(new java.awt.Color(51, 204, 0));
            jButtonProximo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
            jButtonProximo.setForeground(new java.awt.Color(255, 255, 255));
            jButtonProximo.setText("Próximo");
            jButtonProximo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 3, true));
            jButtonProximo.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButtonProximoMouseClicked(evt);
                }
            });
            jButtonProximo.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonProximoActionPerformed(evt);
                }
            });
            jButtonProximo.setVisible(false);

            jButtonAnterior.setBackground(new java.awt.Color(51, 204, 0));
            jButtonAnterior.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
            jButtonAnterior.setForeground(new java.awt.Color(255, 255, 255));
            jButtonAnterior.setText("Anterior");
            jButtonAnterior.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 3, true));
            jButtonAnterior.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButtonAnteriorMouseClicked(evt);
                }
            });
            jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonAnteriorActionPerformed(evt);
                }
            });

            jScrollPane1.setBorder(null);

            jTextArea1.setEditable(false);
            jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
            jTextArea1.setColumns(10);
            jTextArea1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
            jTextArea1.setRows(2);
            jTextArea1.setTabSize(5);
            jTextArea1.setText("Infrome o(s) dia(s) de \npreferência de coleta:");
            jTextArea1.setBorder(null);
            jTextArea1.setOpaque(false);
            jTextArea1.setSelectedTextColor(new java.awt.Color(0, 0, 0));
            jTextArea1.setSelectionColor(new java.awt.Color(255, 255, 255));
            jTextArea1.setLineWrap(true);
            jScrollPane1.setViewportView(jTextArea1);

            jCheckBoxTerca.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
            jCheckBoxTerca.setText("Terça-feira");
            jCheckBoxTerca.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jCheckBoxTercaActionPerformed(evt);
                }
            });

            jCheckBoxQuarta.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
            jCheckBoxQuarta.setText("Quarta-feira");
            jCheckBoxQuarta.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jCheckBoxQuartaActionPerformed(evt);
                }
            });

            jCheckBoxQuinta.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
            jCheckBoxQuinta.setText("Quinta-feira");
            jCheckBoxQuinta.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jCheckBoxQuintaActionPerformed(evt);
                }
            });

            jCheckBoxSexta.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
            jCheckBoxSexta.setText("Sexta-feira");
            jCheckBoxSexta.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jCheckBoxSextaActionPerformed(evt);
                }
            });

            jCheckBoxSabado.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
            jCheckBoxSabado.setText("Sábado");
            jCheckBoxSabado.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jCheckBoxSabadoActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(tela);
           tela.setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(67, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jCheckBoxSexta, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addGap(258, 258, 258))
                        .addComponent(jScrollPane1)
                        .addComponent(jCheckBoxSegunda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBoxTerca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBoxQuarta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBoxQuinta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBoxSabado, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE))
                    .addGap(200, 200, 200))
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jButtonProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(100, 100, 100))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(250, 250, 250)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jCheckBoxSegunda)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBoxTerca)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBoxQuarta)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBoxQuinta)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBoxSexta)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBoxSabado)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(50, 50, 50))
            );

            pack();
            getContentPane().add(tela);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxSegundaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSegundaActionPerformed
        if(exibirProximo())
        	jButtonProximo.setVisible(true);
        else
        	jButtonProximo.setVisible(false);
    }//GEN-LAST:event_jCheckBoxSegundaActionPerformed

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        new CreateRequestView1().main(null);
        this.dispose();
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonAnteriorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAnteriorMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAnteriorMouseClicked

    private void jButtonProximoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonProximoMouseClicked
        chamado.setDisponibilidade("");
    	if(jCheckBoxSegunda.isSelected())
        	chamado.setDisponibilidade("Segunda / ");
        if(jCheckBoxTerca.isSelected())
        	chamado.setDisponibilidade(chamado.getDisponibilidade() + "Terça / ");
        if(jCheckBoxQuarta.isSelected())
        	chamado.setDisponibilidade(chamado.getDisponibilidade() + "Quarta / ");
        if(jCheckBoxQuinta.isSelected())
        	chamado.setDisponibilidade(chamado.getDisponibilidade() + "Quinta / ");
        if(jCheckBoxSexta.isSelected())
        	chamado.setDisponibilidade(chamado.getDisponibilidade() + "Sexta / ");
        if(jCheckBoxSabado.isSelected())
        	chamado.setDisponibilidade(chamado.getDisponibilidade() + "Sábado / ");
        
        CreateRequestView3.setChamado(chamado);
        CreateRequestView3.setConect(conect);
        new CreateRequestView3().main(null);
        this.dispose();
        
       // this.dispose();
    }//GEN-LAST:event_jButtonProximoMouseClicked

    private void jButtonProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProximoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonProximoActionPerformed

    private void jCheckBoxTercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTercaActionPerformed
    	if(exibirProximo())
        	jButtonProximo.setVisible(true);
        else
        	jButtonProximo.setVisible(false);
    }//GEN-LAST:event_jCheckBoxTercaActionPerformed

    private void jCheckBoxQuartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxQuartaActionPerformed
    	if(exibirProximo())
        	jButtonProximo.setVisible(true);
        else
        	jButtonProximo.setVisible(false);
    }//GEN-LAST:event_jCheckBoxQuartaActionPerformed

    private void jCheckBoxQuintaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxQuintaActionPerformed
    	if(exibirProximo())
        	jButtonProximo.setVisible(true);
        else
        	jButtonProximo.setVisible(false);
    }//GEN-LAST:event_jCheckBoxQuintaActionPerformed

    private void jCheckBoxSextaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSextaActionPerformed
    	if(exibirProximo())
        	jButtonProximo.setVisible(true);
        else
        	jButtonProximo.setVisible(false);
    }//GEN-LAST:event_jCheckBoxSextaActionPerformed

    private void jCheckBoxSabadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSabadoActionPerformed
    	if(exibirProximo())
        	jButtonProximo.setVisible(true);
        else
        	jButtonProximo.setVisible(false);
    }//GEN-LAST:event_jCheckBoxSabadoActionPerformed
    
    
    
    boolean exibirProximo() {
    	if(jCheckBoxSegunda.isSelected() || jCheckBoxTerca.isSelected() || jCheckBoxQuarta.isSelected() || jCheckBoxQuinta.isSelected() || jCheckBoxSexta.isSelected() || jCheckBoxSabado.isSelected())
    		return true;
    	return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateRequestView2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateRequestView2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateRequestView2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateRequestView2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateRequestView2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonProximo;
    private javax.swing.JCheckBox jCheckBoxQuarta;
    private javax.swing.JCheckBox jCheckBoxQuinta;
    private javax.swing.JCheckBox jCheckBoxSabado;
    private javax.swing.JCheckBox jCheckBoxSegunda;
    private javax.swing.JCheckBox jCheckBoxSexta;
    private javax.swing.JCheckBox jCheckBoxTerca;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
