/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.ucsal.sage.reports.view;

import java.awt.Color;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.StandardChartTheme;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.renderer.category.StandardBarPainter;
import org.jfree.data.category.DefaultCategoryDataset;

import br.ucsal.sage.reports.controller.ReportsController;
import br.ucsal.sage.reports.model.Reports;
import br.ucsal.sage.user.model.User;
import br.ucsal.sage.user.view.RequestOptionsView;

/**
 *
 * @author Suporte TI
 */
public class ReportsView extends javax.swing.JFrame {

    /**
     * Creates new form Solicitacao_Coleta_1
     */
    
	private static User usuario;
	private static Connection conect;
	private ReportsController controller;
	
	public static void setUsuario(User u) {
		usuario = u;
	}
	
	public static void setConect(Connection c) {
		conect = c;
	}
    public ReportsView() throws SQLException {
        
        initComponents();
       
    setExtendedState(MAXIMIZED_BOTH);
  
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @throws SQLException 
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() throws SQLException {

        jLabel1 = new javax.swing.JLabel();
        jComboBoxAno = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jButtonGerar = new javax.swing.JButton();
        JPanelAreaGrafico = new javax.swing.JPanel();
        jButtonVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Lixo reciclado por:");
        
        controller = new ReportsController();
       
			String [] lista = controller.generateArray(controller.getListYears(conect, usuario.getId_usuario()));
		
        jComboBoxAno.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jComboBoxAno.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxAno.setModel(new javax.swing.DefaultComboBoxModel<>(lista));
        jComboBoxAno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jComboBoxAno.setVisible(false);
        
        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Informe o ano:");
        jLabel2.setVisible(false);

        jComboBoxTipo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jComboBoxTipo.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "ano", "mês/ano" }));
        jComboBoxTipo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jComboBoxTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxTipoMouseClicked(evt);
            }
        });
        jComboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoActionPerformed(evt);
            }
        });

        jButtonGerar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jButtonGerar.setForeground(new java.awt.Color(102, 102, 102));
        jButtonGerar.setText("Gerar");
        jButtonGerar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jButtonGerar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
					jButtonGerarMouseClicked(evt);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

       

        jButtonVoltar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonVoltar.setForeground(new java.awt.Color(51, 204, 0));
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.setBorder(null);
        jButtonVoltar.setContentAreaFilled(false);
        jButtonVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonVoltarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(229, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBoxAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(229, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonVoltar))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGap(164, 164, 164))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(100, 100, 100)
                    .addComponent(jButtonVoltar)
                    .addGap(50, 50, 50)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jComboBoxAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jButtonGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(195, Short.MAX_VALUE))
            );

            pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGerarMouseClicked(java.awt.event.MouseEvent evt) throws SQLException {//GEN-FIRST:event_jButtonGerarMouseClicked
    	JFreeChart chart;
    	
    	if(jComboBoxTipo.getSelectedIndex() == 1) {
    		 ArrayList<Reports> lista = controller.getReportsByYear(conect, usuario.getId_usuario());
    		 
    		
        	DefaultCategoryDataset dataset = new DefaultCategoryDataset();
    		
    		for(Reports r: lista) {
    			dataset.addValue(r.getValor(), String.valueOf(r.getAno()), "");
    		}
        	
    		

    		chart = ChartFactory.createBarChart("Reciclagens por Ano"," ", "Quantidade", dataset);

    	  
    		
        }else {
       	 ArrayList<Reports> lista = controller.getReportsByMonth(conect, usuario.getId_usuario(), Integer.valueOf((String) jComboBoxAno.getSelectedItem()));
		 
 		
     	DefaultCategoryDataset dataset = new DefaultCategoryDataset();
 		
 		for(Reports r: lista) {
 			dataset.addValue(r.getValor(), "", controller.getNameMonth(r.getMes()));
 		}
     	
 		

 		chart = ChartFactory.createBarChart("Ano: " + jComboBoxAno.getSelectedItem(),"Mês", "Quantidade", dataset);

 		
        }
    	
    	CategoryPlot plot = chart.getCategoryPlot();
    	
    	plot.getRenderer().setSeriesPaint(0, Color.GREEN);
    	plot.setBackgroundPaint(Color.white);
    	plot.setDomainGridlinePaint(Color.white);
    	plot.setRangeGridlinePaint(Color.white);
    	
    
    	plot.setOutlineVisible(true);
    	((BarRenderer) plot.getRenderer()).setBarPainter(new StandardBarPainter());
    	
    	ChartPanel chartPanel = new ChartPanel(chart);
 		
 		chartPanel.setPreferredSize(new java.awt.Dimension(800, 450));
 		
 		
 		GraphicsView.setChart(chartPanel);
 		
 		new GraphicsView().main(null); 
    }//GEN-LAST:event_jButtonGerarMouseClicked

    private void jComboBoxTipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxTipoMouseClicked
       
    }//GEN-LAST:event_jComboBoxTipoMouseClicked

    private void jButtonVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVoltarMouseClicked
        new RequestOptionsView().main(null);
        this.dispose();
    }//GEN-LAST:event_jButtonVoltarMouseClicked
    
    private void jComboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {                                              
    	 
     	
     	if(jComboBoxTipo.getSelectedIndex() == 2) {
         	jComboBoxAno.setVisible(true);
         	jLabel2.setVisible(true);
         }
         	else {
         	jComboBoxAno.setVisible(false);
         	jLabel2.setVisible(false);
         	}
     }   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
					new ReportsView().setVisible(true);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGerar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<String> jComboBoxAno;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel JPanelAreaGrafico;
    // End of variables declaration//GEN-END:variables
}
