/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.ucsal.sage.user.view;

import java.awt.GridLayout;
import java.sql.SQLException;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import br.ucsal.sage.collector.view.PageCollectorView;
import br.ucsal.sage.connection.Conexao;
import br.ucsal.sage.requester.view.PageRequesterView;
import br.ucsal.sage.user.controller.UserController;
import br.ucsal.sage.user.model.User;

/**
 *
 * @author Suporte TI
 */

public class LoginView extends javax.swing.JFrame {

	/**
	 * Creates new form Principal
	 */

	private CanvasBackground tela;
	private UserController controller;
	private static Conexao conect = new Conexao();

	public LoginView() {

		initComponents();
		setExtendedState(MAXIMIZED_BOTH);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		setLayout(new GridLayout());
		tela = new CanvasBackground("src/Imagens/login.png");

		jLabelTitulo = new javax.swing.JLabel();
		jTextFieldEmail = new javax.swing.JTextField();
		jPasswordFieldSenha = new javax.swing.JPasswordField();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jButtonLogin = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jButtonCadastro = new javax.swing.JButton();
		jLabelAvisoErro = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabelTitulo.setFont(new java.awt.Font("Arial", 0, 60)); // NOI18N
		jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
		jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelTitulo.setText("SAGE");

		jTextFieldEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

		jPasswordFieldSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

		jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		jLabel2.setText("Email:");
		jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

		jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		jLabel3.setText("Senha:");
		jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

		jButtonLogin.setBackground(new java.awt.Color(0, 204, 0));
		jButtonLogin.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
		jButtonLogin.setForeground(new java.awt.Color(255, 255, 255));
		jButtonLogin.setText("LOGIN");
		jButtonLogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
		jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButtonLoginActionPerformed(evt);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel1.setText("Não tem login?");

		jButtonCadastro.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		jButtonCadastro.setForeground(new java.awt.Color(255, 255, 255));
		jButtonCadastro.setText("Clique aqui");
		jButtonCadastro.setBorder(null);
		jButtonCadastro.setBorderPainted(false);
		jButtonCadastro.setContentAreaFilled(false);
		jButtonCadastro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		jButtonCadastro.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
		jButtonCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButtonCadastroMouseClicked(evt);
			}
		});
		jButtonCadastro.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonCadastroActionPerformed(evt);
			}
		});

		jLabelAvisoErro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
		jLabelAvisoErro.setForeground(new java.awt.Color(204, 0, 0));
		jLabelAvisoErro.setText("");
		jLabelAvisoErro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(tela);
		tela.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap(179, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel3))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addGroup(layout.createSequentialGroup().addGap(82, 82, 82).addComponent(jButtonLogin,
										javax.swing.GroupLayout.PREFERRED_SIZE, 120,
										javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup().addComponent(jLabel1)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButtonCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 159,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addComponent(jTextFieldEmail).addComponent(jPasswordFieldSenha)
								.addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabelAvisoErro, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGap(80, 80, 80)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(46, 46, 46)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jPasswordFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18).addComponent(jButtonLogin).addGap(37, 37, 37)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jButtonCadastro, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGap(29, 29, 29).addComponent(jLabelAvisoErro).addGap(157, 157, 157)));
		pack();
		getContentPane().add(tela);
	}// </editor-fold>//GEN-END:initComponents

	private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {// GEN-FIRST:event_jButtonLoginActionPerformed
		controller = new UserController();

		if (controller.validateLogin(conect.getConexao(), jTextFieldEmail.getText(), jPasswordFieldSenha.getText())) {
			User usuario = controller.getAllUserData(conect.getConexao(), jTextFieldEmail.getText());

			if (usuario.getTipo_usuario() == 2) {
				PageCollectorView.setConect(conect.getConexao());
				PageCollectorView.setUsuario(usuario);
				new PageCollectorView().main(null);
				this.dispose();
			} else {
				PageRequesterView.setConect(conect.getConexao());
				PageRequesterView.setUsuario(usuario);
				new PageRequesterView().main(null);
				this.dispose();
			}

		}

		else {
			jLabelAvisoErro.setText("Login incorreto.");
			jPasswordFieldSenha.setText("");
		}

	}// GEN-LAST:event_jButtonLoginActionPerformed

	private void jButtonCadastroActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonCadastroActionPerformed

		RegistrationView1.setConect(conect.getConexao());
		new RegistrationView1().main(null);
		this.dispose();

	}// GEN-LAST:event_jButtonCadastroActionPerformed

	private void jButtonCadastroMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jButtonCadastroMouseClicked
		// TODO add your handling code here:
	}// GEN-LAST:event_jButtonCadastroMouseClicked

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
	
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				//SpringApplication.run(LoginView.class, args);
				new LoginView().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButtonCadastro;
	private javax.swing.JButton jButtonLogin;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabelTitulo;
	private javax.swing.JPasswordField jPasswordFieldSenha;
	private javax.swing.JTextField jTextFieldEmail;
	private javax.swing.JLabel jLabelAvisoErro;
	// End of variables declaration//GEN-END:variables
}
