/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.ucsal.sage.user.view;

import java.awt.GridLayout;
import java.sql.Connection;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

import br.ucsal.sage.collector.view.PageCollectorView;
import br.ucsal.sage.requester.view.PageRequesterView;
import br.ucsal.sage.user.model.User;

/**
 *
 * @author Suporte TI
 */
public class MyProfileView extends javax.swing.JFrame {

	/**
	 * Creates new form Meu_Perfil
	 */
	private static Connection conect;
	private CanvasBackground tela;
	private static User usuario;

	public static void setConect(Connection c) {
		conect = c;
	}

	

	public static void setUsuario(User u) {
		usuario = u;
	}

	

	public MyProfileView() {
		initComponents();
		setExtendedState(MAXIMIZED_BOTH);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		setLayout(new GridLayout());
		tela = new CanvasBackground("src/Imagens/meu_perfil.png");

		jButtonChamados = new javax.swing.JButton();
		jButtonEditarPerfil = new javax.swing.JButton();
		jButtonSair = new javax.swing.JButton();
		jLabelSeparador = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextAreaEndereco = new javax.swing.JTextArea();
		jLabel2 = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTextAreaSobre = new javax.swing.JTextArea();
		jLabel3 = new javax.swing.JLabel();
		jScrollPane3 = new javax.swing.JScrollPane();
		jTextAreaContato = new javax.swing.JTextArea();
		jLabelNomeUsuario = new javax.swing.JLabel();
		jLabelDataCriacao = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jButtonTelaInicial = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setBackground(new java.awt.Color(255, 255, 255));

		jButtonChamados.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
		jButtonChamados.setText("Chamados");
		jButtonChamados.setBorder(null);
		jButtonChamados.setContentAreaFilled(false);
		jButtonChamados.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButtonChamadosMouseClicked(evt);
			}
		});

		jButtonEditarPerfil.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
		jButtonEditarPerfil.setText("Editar Perfil");
		jButtonEditarPerfil.setBorder(null);
		jButtonEditarPerfil.setContentAreaFilled(false);
		jButtonEditarPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButtonEditarPerfilMouseClicked(evt);
			}
		});

		jButtonSair.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
		jButtonSair.setForeground(new java.awt.Color(255, 0, 51));
		jButtonSair.setText("Sair");
		jButtonSair.setContentAreaFilled(false);
		jButtonSair.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButtonSairMouseClicked(evt);
			}
		});

		jLabelSeparador.setBackground(new java.awt.Color(153, 153, 153));
		jLabelSeparador.setOpaque(true);

		jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		jLabel1.setText("Sobre");

		jScrollPane1.setBorder(null);
		jScrollPane1.setOpaque(false);

		jTextAreaEndereco.setEditable(false);
		jTextAreaEndereco.setColumns(20);
		jTextAreaEndereco.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
		jTextAreaEndereco.setForeground(new java.awt.Color(153, 153, 153));
		jTextAreaEndereco.setRows(5);
		jTextAreaEndereco.setText(usuario.getEndereco() + " / " + usuario.getCidade() + " - " + usuario.getEstado());
		jTextAreaEndereco.setBorder(null);
		jScrollPane1.setViewportView(jTextAreaEndereco);

		jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		jLabel2.setText("Endereço");

		jScrollPane2.setBorder(null);
		jScrollPane2.setOpaque(false);

		jTextAreaSobre.setEditable(false);
		jTextAreaSobre.setColumns(20);
		jTextAreaSobre.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
		jTextAreaSobre.setForeground(new java.awt.Color(153, 153, 153));
		jTextAreaSobre.setRows(5);
		jTextAreaSobre.setText(usuario.getSobre_usuario());
		jTextAreaSobre.setBorder(null);
		jScrollPane2.setViewportView(jTextAreaSobre);

		jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		jLabel3.setText("Contato");

		jScrollPane3.setBorder(null);
		jScrollPane3.setOpaque(false);

		jTextAreaContato.setEditable(false);
		jTextAreaContato.setColumns(20);
		jTextAreaContato.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
		jTextAreaContato.setForeground(new java.awt.Color(153, 153, 153));
		jTextAreaContato.setRows(5);
		jTextAreaContato.setText(usuario.getTelefone() + " / " + usuario.getCelular());
		jTextAreaContato.setBorder(null);
		jScrollPane3.setViewportView(jTextAreaContato);

		jLabelNomeUsuario.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
		jLabelNomeUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabelNomeUsuario.setText(usuario.getNome());

		jLabelDataCriacao.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
		jLabelDataCriacao.setForeground(new java.awt.Color(102, 102, 102));
		jLabelDataCriacao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		LocalDate data = LocalDate.parse(usuario.getData_criacao());
		DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
		jLabelDataCriacao.setText("Desde " + formatter.format(data));

		jLabel4.setIcon(new javax.swing.ImageIcon("src/Imagens/foto_perfil_small.png")); // NOI18N
		jLabel4.setText("");

		jButtonTelaInicial.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
		jButtonTelaInicial.setForeground(new java.awt.Color(51, 153, 0));
		jButtonTelaInicial.setText("Tela Inicial");
		jButtonTelaInicial.setBorder(null);
		jButtonTelaInicial.setContentAreaFilled(false);
		jButtonTelaInicial.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				try {
					jButtonTelaInicialMouseClicked(evt);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(tela);
		tela.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
						.createSequentialGroup().addGap(100, 100, 100)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jButtonEditarPerfil, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jButtonChamados, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jButtonSair, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jLabelSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, 2,
								javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(layout.createSequentialGroup().addGap(50, 50, 50).addComponent(jButtonTelaInicial,
								javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
						.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(layout.createSequentialGroup().addGap(80, 80, 80).addComponent(
										jLabelNomeUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE))
								.addComponent(jLabelDataCriacao, javax.swing.GroupLayout.PREFERRED_SIZE, 143,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(30, 30, 30).addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
								javax.swing.GroupLayout.PREFERRED_SIZE))
						.addComponent(jScrollPane2).addComponent(jScrollPane1).addComponent(jScrollPane3))
				.addGap(200, 200, 200)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(38, 38, 38)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
						.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(layout.createSequentialGroup().addGap(67, 67, 67).addComponent(
										jLabelSeparador, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addGroup(layout.createSequentialGroup().addComponent(jButtonTelaInicial)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jButtonChamados, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(30, 30, 30)
										.addComponent(jButtonEditarPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(0, 0, Short.MAX_VALUE).addComponent(jButtonSair,
												javax.swing.GroupLayout.PREFERRED_SIZE, 31,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGap(19, 19, 19))
						.addGroup(layout.createSequentialGroup()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup()
												.addComponent(jLabelNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE,
														34, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jLabelDataCriacao))
										.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(30, 30, 30).addComponent(jLabel1)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jLabel2)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jLabel3)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
								.addGap(53, 53, 53)))));

		pack();
		getContentPane().add(tela);
	}// </editor-fold>//GEN-END:initComponents

	private void jButtonChamadosMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jButtonChamadosMouseClicked
		RequestOptionsView.setConect(conect);
		RequestOptionsView.setUsuario(usuario);
		new RequestOptionsView().main(null);
		this.dispose();
	}// GEN-LAST:event_jButtonChamadosMouseClicked

	private void jButtonEditarPerfilMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jButtonEditarPerfilMouseClicked
		EditProfileView.setUsuario(usuario);
		EditProfileView.setConect(conect);
		new EditProfileView().main(null);
		this.dispose();
	}// GEN-LAST:event_jButtonEditarPerfilMouseClicked

	private void jButtonSairMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jButtonSairMouseClicked
		new LoginView().main(null);
		this.dispose();
	}// GEN-LAST:event_jButtonSairMouseClicked

	private void jButtonTelaInicialMouseClicked(java.awt.event.MouseEvent evt) throws SQLException {
		if (usuario.getTipo_usuario() == 1)
			new PageRequesterView().main(null);
		else
			new PageCollectorView().main(null);

		this.dispose();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MyProfileView.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MyProfileView.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MyProfileView.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MyProfileView.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MyProfileView().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButtonEditarPerfil;
	private javax.swing.JButton jButtonChamados;
	private javax.swing.JButton jButtonSair;
	private javax.swing.JButton jButtonTelaInicial;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabelDataCriacao;
	private javax.swing.JLabel jLabelNomeUsuario;
	private javax.swing.JLabel jLabelSeparador;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JTextArea jTextAreaContato;
	private javax.swing.JTextArea jTextAreaEndereco;
	private javax.swing.JTextArea jTextAreaSobre;
	// End of variables declaration//GEN-END:variables
}
