/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.ucsal.sage.user.view;

import java.awt.GridLayout;
import java.sql.Connection;

/**
 *
 * @author Suporte TI
 */
public class RegistrationView1 extends javax.swing.JFrame {

	/**
	 * Creates new form Principal
	 */

	private CanvasBackground tela;
	private static Connection conect;

	static void setConect(Connection c) {
		conect = c;
	}

	public RegistrationView1() {

		initComponents();
		setExtendedState(MAXIMIZED_BOTH);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		setLayout(new GridLayout());
		tela = new CanvasBackground("src/Imagens/cadastro_1.png");

		jLabelTitulo = new javax.swing.JLabel();
		jButtonEscola = new javax.swing.JButton();
		jButtonColetora = new javax.swing.JButton();
		jButtonVoltar = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabelTitulo.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
		jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelTitulo.setText("Você é:");

		jButtonEscola.setBackground(new java.awt.Color(51, 204, 0));
		jButtonEscola.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		jButtonEscola.setForeground(new java.awt.Color(255, 255, 255));
		jButtonEscola.setText("Escola");
		jButtonEscola.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED,
				new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51),
				new java.awt.Color(0, 102, 51)));
		jButtonEscola.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonEscolaActionPerformed(evt);
			}
		});

		jButtonColetora.setBackground(new java.awt.Color(51, 204, 0));
		jButtonColetora.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		jButtonColetora.setForeground(new java.awt.Color(255, 255, 255));
		jButtonColetora.setText("Coletora");
		jButtonColetora.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED,
				new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51),
				new java.awt.Color(0, 102, 51)));
		jButtonColetora.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonColetoraActionPerformed(evt);
			}
		});

		jButtonVoltar.setBackground(new java.awt.Color(51, 204, 0));
		jButtonVoltar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		jButtonVoltar.setForeground(new java.awt.Color(255, 255, 255));
		jButtonVoltar.setText("Voltar");
		jButtonVoltar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED,
				new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51),
				new java.awt.Color(0, 102, 51)));
		jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonVoltarActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(tela);
		tela.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap(100, Short.MAX_VALUE)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
								.addComponent(jButtonEscola, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
								.addComponent(jButtonColetora, javax.swing.GroupLayout.Alignment.LEADING,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE))
								.addGap(300, 300, 300))
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								layout.createSequentialGroup()
										.addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 112,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(100, 100, 100)))));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(50, 50, 50)
						.addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, Short.MAX_VALUE)
						.addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(41, 41, 41)
						.addComponent(jButtonEscola, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18).addComponent(jButtonColetora, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(217, Short.MAX_VALUE)));

		pack();

		getContentPane().add(tela);

	}// </editor-fold>//GEN-END:initComponents

	private void jButtonEscolaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonEscolaActionPerformed

		RegistrationView2.setConect(conect);
		RegistrationView2.setTipoUsuario(1);
		new RegistrationView2().main(null);
		this.dispose();
	}// GEN-LAST:event_jButtonEscolaActionPerformed

	private void jButtonColetoraActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonColetoraActionPerformed
		RegistrationView2.setConect(conect);
		RegistrationView2.setTipoUsuario(2);
		new RegistrationView2().main(null);
		this.dispose();

	}// GEN-LAST:event_jButtonColetoraActionPerformed

	private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonVoltarActionPerformed

		new LoginView().main(null);
		this.dispose();
	}// GEN-LAST:event_jButtonVoltarActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(RegistrationView1.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(RegistrationView1.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(RegistrationView1.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(RegistrationView1.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new RegistrationView1().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButtonColetora;
	private javax.swing.JButton jButtonEscola;
	private javax.swing.JButton jButtonVoltar;
	private javax.swing.JLabel jLabelTitulo;
	// End of variables declaration//GEN-END:variables
}
