/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.ucsal.sage.user.view;

import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.ParseException;

import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

import br.ucsal.sage.collector.view.PageCollectorView;
import br.ucsal.sage.requester.view.PageRequesterView;
import br.ucsal.sage.user.controller.UserController;
import br.ucsal.sage.user.model.Adress;
import br.ucsal.sage.user.model.User;

/**
 *
 * @author Suporte TI
 */
public class RegistrationView2 extends javax.swing.JFrame {

	/**
	 * Creates new form Principal
	 */

	private static int tipo_usuario;
	private CanvasBackground tela;
	private MaskFormatter CNPJMask;
	private MaskFormatter TelefoneMask;
	private MaskFormatter CelularMask;
	private MaskFormatter CEPMask;
	private UserController controller;
	private static Connection conect;

	static void setConect(Connection c) {
		conect = c;
	}

	static void setTipoUsuario(int i) {
		tipo_usuario = i;
	}

	public RegistrationView2() {

		initComponents();
		setExtendedState(MAXIMIZED_BOTH);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		setLayout(new GridLayout());
		tela = new CanvasBackground("src/Imagens/cadastro_2.png");

		jLabel1 = new javax.swing.JLabel();
		jTextFieldCNPJ = new javax.swing.JFormattedTextField();
		jLabel9 = new javax.swing.JLabel();
		jTextFieldNome = new javax.swing.JTextField();
		jLabel10 = new javax.swing.JLabel();
		jTextFieldLogradouro = new javax.swing.JTextField();
		jLabel11 = new javax.swing.JLabel();
		jTextFieldEmail = new javax.swing.JTextField();
		jLabel12 = new javax.swing.JLabel();
		jTextFieldCep = new javax.swing.JFormattedTextField();
		jLabel13 = new javax.swing.JLabel();
		jTextFieldTelefone = new javax.swing.JFormattedTextField();
		jButtonSalvar = new javax.swing.JButton();
		jButtonCancelar = new javax.swing.JButton();
		jLabel14 = new javax.swing.JLabel();
		jTextFieldComplemento = new javax.swing.JTextField();
		jLabel15 = new javax.swing.JLabel();
		jTextFieldBairro = new javax.swing.JTextField();
		jLabel16 = new javax.swing.JLabel();
		jTextFieldApelido = new javax.swing.JTextField();
		jLabel17 = new javax.swing.JLabel();
		jTextFieldSenha = new javax.swing.JTextField();
		jButtonBuscar = new javax.swing.JButton();
		jLabel18 = new javax.swing.JLabel();
		jTextFieldCidade = new javax.swing.JTextField();
		jLabel19 = new javax.swing.JLabel();
		jTextFieldUF = new javax.swing.JTextField();
		jLabel20 = new javax.swing.JLabel();
		jTextFieldCelular = new javax.swing.JFormattedTextField();
		jLabelAvisoErro = new javax.swing.JLabel();

		try {
			CNPJMask = new MaskFormatter("##.###.###/####-##");
			TelefoneMask = new MaskFormatter("(##) ####-####");
			CelularMask = new MaskFormatter("(##) #####-####");
			CEPMask = new MaskFormatter("########");
		} catch (ParseException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
		jLabel1.setText("CNPJ:");

		jTextFieldCNPJ.setBackground(new java.awt.Color(0, 0, 0, 0));
		jTextFieldCNPJ.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
		jTextFieldCNPJ.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
		jTextFieldCNPJ.setValue(null);
		jTextFieldCNPJ.setFormatterFactory(new DefaultFormatterFactory(CNPJMask));

		jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
		jLabel9.setText("Nome:");

		jTextFieldNome.setBackground(new java.awt.Color(0, 0, 0, 0));
		jTextFieldNome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
		jTextFieldNome.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

		jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
		jLabel10.setText("E-mail:");

		jTextFieldLogradouro.setBackground(new java.awt.Color(102, 102, 102));
		jTextFieldLogradouro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
		jTextFieldLogradouro.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

		jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
		jLabel11.setText("CEP:");

		jTextFieldEmail.setBackground(new java.awt.Color(0, 0, 0, 0));
		jTextFieldEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
		jTextFieldEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

		jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
		jLabel12.setText("Logradouro:");

		jTextFieldCep.setBackground(new java.awt.Color(0, 0, 0, 0));
		jTextFieldCep.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
		jTextFieldCep.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
		jTextFieldCep.setValue(null);
		jTextFieldCep.setFormatterFactory(new DefaultFormatterFactory(CEPMask));

		jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
		jLabel13.setText("Telefone:");

		jTextFieldTelefone.setBackground(new java.awt.Color(0, 0, 0, 0));
		jTextFieldTelefone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
		jTextFieldTelefone.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
		jTextFieldTelefone.setValue(null);
		jTextFieldTelefone.setFormatterFactory(new DefaultFormatterFactory(TelefoneMask));

		jButtonSalvar.setBackground(new java.awt.Color(51, 204, 0));
		jButtonSalvar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		jButtonSalvar.setForeground(new java.awt.Color(255, 255, 255));
		jButtonSalvar.setText("Salvar");
		jButtonSalvar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 51), 1, true));
		jButtonSalvar.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				try {
					jButtonSalvarMouseClicked(null);
				} catch (SQLException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}

			}
		});

		jButtonCancelar.setBackground(new java.awt.Color(51, 204, 0));
		jButtonCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		jButtonCancelar.setForeground(new java.awt.Color(255, 255, 255));
		jButtonCancelar.setText("Cancelar");
		jButtonCancelar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 51), 1, true));
		jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonCancelarActionPerformed(evt);
			}
		});

		jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
		jLabel14.setText("Complemento:");

		jTextFieldComplemento.setBackground(new java.awt.Color(0, 0, 0, 0));
		jTextFieldComplemento.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
		jTextFieldComplemento.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

		jLabel15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
		jLabel15.setText("Bairro:");

		jTextFieldBairro.setBackground(new java.awt.Color(102, 102, 102));
		jTextFieldBairro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
		jTextFieldBairro.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

		jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
		jLabel16.setText("Apelido:");

		jTextFieldApelido.setBackground(new java.awt.Color(0, 0, 0, 0));
		jTextFieldApelido.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
		jTextFieldApelido.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

		jLabel17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
		jLabel17.setText("Senha:");

		jTextFieldSenha.setBackground(new java.awt.Color(0, 0, 0, 0));
		jTextFieldSenha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
		jTextFieldSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

		jButtonBuscar.setBackground(new java.awt.Color(51, 204, 0));
		jButtonBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		jButtonBuscar.setForeground(new java.awt.Color(255, 255, 255));
		jButtonBuscar.setText("Buscar");
		jButtonBuscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 51), 1, true));
		jButtonBuscar.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				try {
					jButtonBuscarMouseClicked(null);
				} catch (SQLException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}

			}
		});

		jLabel18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
		jLabel18.setText("Cidade:");

		jTextFieldCidade.setBackground(new java.awt.Color(102, 102, 102));
		jTextFieldCidade.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
		jTextFieldCidade.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

		jLabel19.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
		jLabel19.setText("UF:");

		jTextFieldUF.setBackground(new java.awt.Color(102, 102, 102));
		jTextFieldUF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
		jTextFieldUF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

		jLabel20.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
		jLabel20.setText("Celular:");

		jTextFieldCelular.setBackground(new java.awt.Color(0, 0, 0, 0));
		jTextFieldCelular.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
		jTextFieldCelular.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
		jTextFieldCelular.setValue(null);
		jTextFieldCelular.setFormatterFactory(new DefaultFormatterFactory(CelularMask));

		jLabelAvisoErro.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
		jLabelAvisoErro.setForeground(new java.awt.Color(204, 0, 0));
		jLabelAvisoErro.setText("");

		jTextFieldBairro.setEnabled(false);
		jTextFieldCidade.setEnabled(false);
		jTextFieldLogradouro.setEnabled(false);
		jTextFieldUF.setEnabled(false);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(tela);
		tela.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addGap(30, 30, 30)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jTextFieldTelefone).addComponent(jTextFieldEmail)
												.addComponent(jTextFieldCNPJ).addComponent(jTextFieldLogradouro)
												.addGroup(layout.createSequentialGroup().addComponent(jTextFieldCep)
														.addGap(37, 37, 37).addComponent(jButtonBuscar,
																javax.swing.GroupLayout.PREFERRED_SIZE, 88,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addComponent(jTextFieldNome)
												.addGroup(layout
														.createSequentialGroup()
														.addGroup(layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jLabel13,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 80,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(jLabel12,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 80,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(jLabel11,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 80,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(jLabel10,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 80,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(jLabel9,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 80,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(jLabel1,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 80,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGap(220, 220, 220))))
								.addGroup(layout.createSequentialGroup()
										.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 86,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addGap(48, 48, 48).addGroup(
										layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(layout.createSequentialGroup().addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE,
																91, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jTextFieldComplemento)).addGap(33, 33, 33)
														.addGroup(layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jTextFieldBairro).addComponent(jLabel15,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 91,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
														.createSequentialGroup()
														.addGroup(layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jLabel18,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 80,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(jTextFieldCidade,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 308,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGap(18, 18, Short.MAX_VALUE)
														.addGroup(layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jTextFieldUF,
																		javax.swing.GroupLayout.DEFAULT_SIZE, 136,
																		Short.MAX_VALUE)
																.addComponent(
																		jLabel19,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 80,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
														.createSequentialGroup().addGap(162, 162, 162)
														.addGroup(layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jLabel16,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 80,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(jTextFieldApelido)
																.addComponent(jLabel17,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 80,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(jTextFieldSenha)
																.addComponent(jLabel20,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 80,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(jTextFieldCelular)))
												.addGroup(layout.createSequentialGroup()
														.addComponent(jButtonCancelar,
																javax.swing.GroupLayout.PREFERRED_SIZE, 86,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(0, 0, Short.MAX_VALUE)))
										.addGap(42, 42, 42))
								.addGroup(layout.createSequentialGroup().addGap(75, 75, 75)
										.addComponent(jLabelAvisoErro, javax.swing.GroupLayout.PREFERRED_SIZE, 700,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jLabel1)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jTextFieldCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabelAvisoErro))
						.addGap(18, 18, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel9).addComponent(jLabel16))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jTextFieldNome).addComponent(jTextFieldApelido))
						.addGap(18, 18, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel10).addComponent(jLabel17))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jTextFieldEmail).addComponent(jTextFieldSenha))
						.addGap(18, 18, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel11).addComponent(jLabel18).addComponent(jLabel19))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jTextFieldCep).addComponent(jButtonBuscar).addComponent(jTextFieldCidade)
								.addComponent(jTextFieldUF))
						.addGap(18, 18, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel12).addComponent(jLabel14).addComponent(jLabel15))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jTextFieldLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jTextFieldComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel13).addComponent(jLabel20))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jTextFieldCelular))
						.addGap(18, 33, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(50, 50, 50)));

		pack();

		getContentPane().add(tela);
	}// </editor-fold>//GEN-END:initComponents

	private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonCancelarActionPerformed

		new LoginView().main(null);
		this.dispose();
	}// GEN-LAST:event_jButtonCancelarActionPerformed

	private void jButtonSalvarMouseClicked(java.awt.event.MouseEvent evt) throws SQLException {
		confereCamposObrigatorios();
		controller = new UserController();
		String endereco = jTextFieldLogradouro.getText() + ", " + jTextFieldComplemento.getText() + " - "
				+ jTextFieldBairro.getText().replaceAll("'", "''") + ", CEP: " + jTextFieldCep.getText();

		if (controller.createUser(conect, jTextFieldEmail.getText(), jTextFieldSenha.getText(),
				jTextFieldNome.getText(), jTextFieldApelido.getText(), tipo_usuario, "", jTextFieldCNPJ.getText(),
				endereco, jTextFieldCidade.getText(), jTextFieldUF.getText(), jTextFieldTelefone.getText(),
				jTextFieldCelular.getText())) {
			User usuario = controller.getAllUserData(conect, jTextFieldEmail.getText());
			if (usuario.getTipo_usuario() == 2) {
				PageCollectorView.setUsuario(usuario);
				new PageCollectorView().main(null);
				this.dispose();
			} else {
				PageRequesterView.setUsuario(usuario);
				new PageRequesterView().main(null);
				this.dispose();
			}

		}

		else
			jLabelAvisoErro.setText(
					"ERRO! Possíveis causas: e-mail/CNPJ já foi cadastrado / e-mail é inválido / não preencheu todos os campos obrigatórios.");

	}

	private void jButtonBuscarMouseClicked(java.awt.event.MouseEvent evt) throws SQLException {
		controller = new UserController();

		Adress endereco = controller.getAdressByZipCode(jTextFieldCep.getText());

		if (endereco.getLogradouro() == null) {
			jTextFieldCidade.setText("");
			jTextFieldUF.setText("");
			jTextFieldBairro.setText("");
			jTextFieldLogradouro.setText("");
			jTextFieldBairro.setEnabled(true);
			jTextFieldCidade.setEnabled(true);
			jTextFieldLogradouro.setEnabled(true);
			jTextFieldUF.setEnabled(true);
			jTextFieldBairro.setBackground(new java.awt.Color(0, 0, 0, 0));
			jTextFieldCidade.setBackground(new java.awt.Color(0, 0, 0, 0));
			jTextFieldLogradouro.setBackground(new java.awt.Color(0, 0, 0, 0));
			jTextFieldUF.setBackground(new java.awt.Color(0, 0, 0, 0));
			jLabelAvisoErro.setText("CEP não encontrado. Informe um novo CEP ou preencha o endereço manualmente.");

		} else {
			jLabelAvisoErro.setText("");
			jTextFieldBairro.setBackground(new java.awt.Color(102, 102, 102));
			jTextFieldCidade.setBackground(new java.awt.Color(102, 102, 102));
			jTextFieldLogradouro.setBackground(new java.awt.Color(102, 102, 102));
			jTextFieldUF.setBackground(new java.awt.Color(102, 102, 102));
			jTextFieldBairro.setEnabled(false);
			jTextFieldCidade.setEnabled(false);
			jTextFieldLogradouro.setEnabled(false);
			jTextFieldUF.setEnabled(false);
			jTextFieldBairro.setText(endereco.getBairro());
			jTextFieldCidade.setText("Salvador");
			jTextFieldLogradouro.setText(endereco.getLogradouro());
			jTextFieldUF.setText("Bahia");

		}
	}

	public void confereCamposObrigatorios() {
		if (jTextFieldApelido.getText().replaceAll(" ", "").equals(""))
			jTextFieldApelido.setBorder(new javax.swing.border.LineBorder(Color.RED, 3, true));
		else
			jTextFieldApelido.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

		if (jTextFieldCNPJ.getText().replaceAll(".", "").replaceAll("-", "").replaceAll("/", "").equals(""))
			jTextFieldCNPJ.setBorder(new javax.swing.border.LineBorder(Color.RED, 3, true));
		else
			jTextFieldCNPJ.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

		if (jTextFieldNome.getText().replaceAll(" ", "").equals(""))
			jTextFieldNome.setBorder(new javax.swing.border.LineBorder(Color.RED, 3, true));
		else
			jTextFieldNome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

		if (jTextFieldEmail.getText().replaceAll(" ", "").equals(""))
			jTextFieldEmail.setBorder(new javax.swing.border.LineBorder(Color.RED, 3, true));
		else
			jTextFieldEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

		if (jTextFieldSenha.getText().replaceAll(" ", "").equals(""))
			jTextFieldSenha.setBorder(new javax.swing.border.LineBorder(Color.RED, 3, true));
		else
			jTextFieldSenha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

		if (jTextFieldCep.getText().replaceAll(" ", "").equals(""))
			jTextFieldCep.setBorder(new javax.swing.border.LineBorder(Color.RED, 3, true));
		else
			jTextFieldCep.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

		if (jTextFieldCidade.getText().replaceAll(" ", "").equals(""))
			jTextFieldCidade.setBorder(new javax.swing.border.LineBorder(Color.RED, 3, true));
		else
			jTextFieldCidade.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

		if (jTextFieldUF.getText().replaceAll(" ", "").equals(""))
			jTextFieldUF.setBorder(new javax.swing.border.LineBorder(Color.RED, 3, true));
		else
			jTextFieldUF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

		if (jTextFieldBairro.getText().replaceAll(" ", "").equals(""))
			jTextFieldBairro.setBorder(new javax.swing.border.LineBorder(Color.RED, 3, true));
		else
			jTextFieldBairro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

		if (jTextFieldLogradouro.getText().replaceAll(" ", "").equals(""))
			jTextFieldLogradouro.setBorder(new javax.swing.border.LineBorder(Color.RED, 3, true));
		else
			jTextFieldLogradouro
					.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(RegistrationView2.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(RegistrationView2.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(RegistrationView2.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(RegistrationView2.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new RegistrationView2().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButtonBuscar;
	private javax.swing.JButton jButtonCancelar;
	private javax.swing.JButton jButtonSalvar;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JLabel jLabel19;
	private javax.swing.JLabel jLabel20;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JLabel jLabelAvisoErro;
	private javax.swing.JTextField jTextFieldApelido;
	private javax.swing.JTextField jTextFieldBairro;
	private javax.swing.JFormattedTextField jTextFieldCNPJ;
	private javax.swing.JFormattedTextField jTextFieldCep;
	private javax.swing.JTextField jTextFieldCidade;
	private javax.swing.JTextField jTextFieldComplemento;
	private javax.swing.JTextField jTextFieldEmail;
	private javax.swing.JTextField jTextFieldLogradouro;
	private javax.swing.JTextField jTextFieldNome;
	private javax.swing.JTextField jTextFieldSenha;
	private javax.swing.JFormattedTextField jTextFieldTelefone;
	private javax.swing.JFormattedTextField jTextFieldCelular;
	private javax.swing.JTextField jTextFieldUF;
	// End of variables declaration//GEN-END:variables
}
