/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.ucsal.sage.user.view;

import java.awt.GridLayout;
import java.sql.Connection;
import java.sql.SQLException;

import br.ucsal.sage.reports.view.ReportsView;
import br.ucsal.sage.request.view.MyRequests;
import br.ucsal.sage.user.model.User;

/**
 *
 * @author Suporte TI
 */
public class RequestOptionsView extends javax.swing.JFrame {

	/**
	 * Creates new form Solicitacao_Coleta_1
	 */
	private static Connection conect;
	private static User usuario;
	private CanvasBackground tela;

	public static void setUsuario(User u) {
		usuario = u;
	}

	public static void setConect(Connection c) {
		conect = c;
	}

	public RequestOptionsView() {

		initComponents();
		setExtendedState(MAXIMIZED_BOTH);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		setLayout(new GridLayout());
		tela = new CanvasBackground("src/Imagens/fundo_chamados.png");

		jButtonRelatorios = new javax.swing.JButton();
		jButtonMinhasSolicitacoes = new javax.swing.JButton();
		jButtonVoltar = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jButtonRelatorios.setBackground(new java.awt.Color(0, 153, 51));
		jButtonRelatorios.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		jButtonRelatorios.setForeground(new java.awt.Color(255, 255, 255));
		jButtonRelatorios.setText("Relatório de solicitações");
		jButtonRelatorios.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
		jButtonRelatorios.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				try {
					jButtonRelatoriosMouseClicked(evt);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		jButtonMinhasSolicitacoes.setBackground(new java.awt.Color(0, 153, 51));
		jButtonMinhasSolicitacoes.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		jButtonMinhasSolicitacoes.setForeground(new java.awt.Color(255, 255, 255));
		jButtonMinhasSolicitacoes.setText("Minhas solicitações");
		jButtonMinhasSolicitacoes
				.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
		jButtonMinhasSolicitacoes.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				try {
					jButtonMinhasSolicitacoesMouseClicked(evt);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		jButtonVoltar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
		jButtonVoltar.setForeground(new java.awt.Color(255, 255, 255));
		jButtonVoltar.setText("Voltar");
		jButtonVoltar.setBorder(null);
		jButtonVoltar.setContentAreaFilled(false);
		jButtonVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButtonVoltarMouseClicked(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(tela);
		tela.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jButtonMinhasSolicitacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 258,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jButtonRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 258,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(layout.createSequentialGroup().addGap(200, 200, 200)
						.addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 71,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jButtonMinhasSolicitacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 70,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(jButtonRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 70,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
						.addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 25,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(100, 100, 100)));

		pack();
		getContentPane().add(tela);
	}// </editor-fold>//GEN-END:initComponents

	private void jButtonMinhasSolicitacoesMouseClicked(java.awt.event.MouseEvent evt) throws SQLException {// GEN-FIRST:event_jButtonMinhasSolicitacoesMouseClicked
		MyRequests.setConect(conect);
		MyRequests.setUsuario(usuario);
		MyRequests.setContexto(1);
		new MyRequests().main(null);
		this.dispose();
	}// GEN-LAST:event_jButtonMinhasSolicitacoesMouseClicked

	private void jButtonRelatoriosMouseClicked(java.awt.event.MouseEvent evt) throws SQLException {// GEN-FIRST:event_jButtonRelatoriosMouseClicked
		ReportsView.setConect(conect);
		ReportsView.setUsuario(usuario);
		new ReportsView().main(null);
		this.dispose();
	}// GEN-LAST:event_jButtonRelatoriosMouseClicked

	private void jButtonVoltarMouseClicked(java.awt.event.MouseEvent evt) {
		new MyProfileView().main(null);
		this.dispose();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(RequestOptionsView.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(RequestOptionsView.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(RequestOptionsView.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(RequestOptionsView.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new RequestOptionsView().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButtonMinhasSolicitacoes;
	private javax.swing.JButton jButtonRelatorios;
	private javax.swing.JButton jButtonVoltar;
	// End of variables declaration//GEN-END:variables
}
